export interface SurahInfo {
  number: number;
  nameAr: string;
  nameEn: string;
  englishTranslation: string;
  ayahs: number;
  revelationType: 'Meccan' | 'Medinan';
}

export const SURAHS: SurahInfo[] = [
  { number: 1, nameAr: 'الفاتحة', nameEn: 'Al-Fatiha', englishTranslation: 'The Opening', ayahs: 7, revelationType: 'Meccan' },
  { number: 2, nameAr: 'البقرة', nameEn: 'Al-Baqarah', englishTranslation: 'The Cow', ayahs: 286, revelationType: 'Medinan' },
  { number: 3, nameAr: 'آل عمران', nameEn: 'Aal-Imran', englishTranslation: 'Family of Imran', ayahs: 200, revelationType: 'Medinan' },
  { number: 4, nameAr: 'النساء', nameEn: 'An-Nisa', englishTranslation: 'The Women', ayahs: 176, revelationType: 'Medinan' },
  { number: 5, nameAr: 'المائدة', nameEn: 'Al-Ma\'idah', englishTranslation: 'The Table Spread', ayahs: 120, revelationType: 'Medinan' },
  { number: 6, nameAr: 'الأنعام', nameEn: 'Al-An\'am', englishTranslation: 'The Cattle', ayahs: 165, revelationType: 'Meccan' },
  { number: 7, nameAr: 'الأعراف', nameEn: 'Al-A\'raf', englishTranslation: 'The Heights', ayahs: 206, revelationType: 'Meccan' },
  { number: 8, nameAr: 'الأنفال', nameEn: 'Al-Anfal', englishTranslation: 'The Spoils of War', ayahs: 75, revelationType: 'Medinan' },
  { number: 9, nameAr: 'التوبة', nameEn: 'At-Tawbah', englishTranslation: 'The Repentance', ayahs: 129, revelationType: 'Medinan' },
  { number: 10, nameAr: 'يونس', nameEn: 'Yunus', englishTranslation: 'Jonah', ayahs: 109, revelationType: 'Meccan' },
  { number: 11, nameAr: 'هود', nameEn: 'Hud', englishTranslation: 'Hud', ayahs: 123, revelationType: 'Meccan' },
  { number: 12, nameAr: 'يوسف', nameEn: 'Yusuf', englishTranslation: 'Joseph', ayahs: 111, revelationType: 'Meccan' },
  { number: 13, nameAr: 'الرعد', nameEn: 'Ar-Ra\'d', englishTranslation: 'The Thunder', ayahs: 43, revelationType: 'Medinan' },
  { number: 14, nameAr: 'إبراهيم', nameEn: 'Ibrahim', englishTranslation: 'Abraham', ayahs: 52, revelationType: 'Meccan' },
  { number: 15, nameAr: 'الحجر', nameEn: 'Al-Hijr', englishTranslation: 'The Rocky Tract', ayahs: 99, revelationType: 'Meccan' },
  { number: 16, nameAr: 'النحل', nameEn: 'An-Nahl', englishTranslation: 'The Bee', ayahs: 128, revelationType: 'Meccan' },
  { number: 17, nameAr: 'الإسراء', nameEn: 'Al-Isra', englishTranslation: 'The Night Journey', ayahs: 111, revelationType: 'Meccan' },
  { number: 18, nameAr: 'الكهف', nameEn: 'Al-Kahf', englishTranslation: 'The Cave', ayahs: 110, revelationType: 'Meccan' },
  { number: 19, nameAr: 'مريم', nameEn: 'Maryam', englishTranslation: 'Mary', ayahs: 98, revelationType: 'Meccan' },
  { number: 20, nameAr: 'طه', nameEn: 'Ta-Ha', englishTranslation: 'Ta-Ha', ayahs: 135, revelationType: 'Meccan' },
  { number: 21, nameAr: 'الأنبياء', nameEn: 'Al-Anbiya', englishTranslation: 'The Prophets', ayahs: 112, revelationType: 'Meccan' },
  { number: 22, nameAr: 'الحج', nameEn: 'Al-Hajj', englishTranslation: 'The Pilgrimage', ayahs: 78, revelationType: 'Medinan' },
  { number: 23, nameAr: 'المؤمنون', nameEn: 'Al-Mu\'minun', englishTranslation: 'The Believers', ayahs: 118, revelationType: 'Meccan' },
  { number: 24, nameAr: 'النور', nameEn: 'An-Nur', englishTranslation: 'The Light', ayahs: 64, revelationType: 'Medinan' },
  { number: 25, nameAr: 'الفرقان', nameEn: 'Al-Furqan', englishTranslation: 'The Criterion', ayahs: 77, revelationType: 'Meccan' },
  { number: 26, nameAr: 'الشعراء', nameEn: 'Ash-Shu\'ara', englishTranslation: 'The Poets', ayahs: 227, revelationType: 'Meccan' },
  { number: 27, nameAr: 'النمل', nameEn: 'An-Naml', englishTranslation: 'The Ant', ayahs: 93, revelationType: 'Meccan' },
  { number: 28, nameAr: 'القصص', nameEn: 'Al-Qasas', englishTranslation: 'The Stories', ayahs: 88, revelationType: 'Meccan' },
  { number: 29, nameAr: 'العنكبوت', nameEn: 'Al-Ankabut', englishTranslation: 'The Spider', ayahs: 69, revelationType: 'Meccan' },
  { number: 30, nameAr: 'الروم', nameEn: 'Ar-Rum', englishTranslation: 'The Romans', ayahs: 60, revelationType: 'Meccan' },
  { number: 31, nameAr: 'لقمان', nameEn: 'Luqman', englishTranslation: 'Luqman', ayahs: 34, revelationType: 'Meccan' },
  { number: 32, nameAr: 'السجدة', nameEn: 'As-Sajdah', englishTranslation: 'The Prostration', ayahs: 30, revelationType: 'Meccan' },
  { number: 33, nameAr: 'الأحزاب', nameEn: 'Al-Ahzab', englishTranslation: 'The Combined Forces', ayahs: 73, revelationType: 'Medinan' },
  { number: 34, nameAr: 'سبأ', nameEn: 'Saba', englishTranslation: 'Sheba', ayahs: 54, revelationType: 'Meccan' },
  { number: 35, nameAr: 'فاطر', nameEn: 'Fatir', englishTranslation: 'The Originator', ayahs: 45, revelationType: 'Meccan' },
  { number: 36, nameAr: 'يس', nameEn: 'Ya-Sin', englishTranslation: 'Ya-Sin', ayahs: 83, revelationType: 'Meccan' },
  { number: 37, nameAr: 'الصافات', nameEn: 'As-Saffat', englishTranslation: 'Those in Ranks', ayahs: 182, revelationType: 'Meccan' },
  { number: 38, nameAr: 'ص', nameEn: 'Sad', englishTranslation: 'Sad', ayahs: 88, revelationType: 'Meccan' },
  { number: 39, nameAr: 'الزمر', nameEn: 'Az-Zumar', englishTranslation: 'The Troops', ayahs: 75, revelationType: 'Meccan' },
  { number: 40, nameAr: 'غافر', nameEn: 'Ghafir', englishTranslation: 'The Forgiver', ayahs: 85, revelationType: 'Meccan' },
  { number: 41, nameAr: 'فصلت', nameEn: 'Fussilat', englishTranslation: 'Explained in Detail', ayahs: 54, revelationType: 'Meccan' },
  { number: 42, nameAr: 'الشورى', nameEn: 'Ash-Shura', englishTranslation: 'The Consultation', ayahs: 53, revelationType: 'Meccan' },
  { number: 43, nameAr: 'الزخرف', nameEn: 'Az-Zukhruf', englishTranslation: 'The Ornaments', ayahs: 89, revelationType: 'Meccan' },
  { number: 44, nameAr: 'الدخان', nameEn: 'Ad-Dukhan', englishTranslation: 'The Smoke', ayahs: 59, revelationType: 'Meccan' },
  { number: 45, nameAr: 'الجاثية', nameEn: 'Al-Jathiyah', englishTranslation: 'The Crouching', ayahs: 37, revelationType: 'Meccan' },
  { number: 46, nameAr: 'الأحقاف', nameEn: 'Al-Ahqaf', englishTranslation: 'The Wind-Curved Sandhills', ayahs: 35, revelationType: 'Meccan' },
  { number: 47, nameAr: 'محمد', nameEn: 'Muhammad', englishTranslation: 'Muhammad', ayahs: 38, revelationType: 'Medinan' },
  { number: 48, nameAr: 'الفتح', nameEn: 'Al-Fath', englishTranslation: 'The Victory', ayahs: 29, revelationType: 'Medinan' },
  { number: 49, nameAr: 'الحجرات', nameEn: 'Al-Hujurat', englishTranslation: 'The Rooms', ayahs: 18, revelationType: 'Medinan' },
  { number: 50, nameAr: 'ق', nameEn: 'Qaf', englishTranslation: 'Qaf', ayahs: 45, revelationType: 'Meccan' },
  { number: 51, nameAr: 'الذاريات', nameEn: 'Adh-Dhariyat', englishTranslation: 'The Winnowing Winds', ayahs: 60, revelationType: 'Meccan' },
  { number: 52, nameAr: 'الطور', nameEn: 'At-Tur', englishTranslation: 'The Mount', ayahs: 49, revelationType: 'Meccan' },
  { number: 53, nameAr: 'النجم', nameEn: 'An-Najm', englishTranslation: 'The Star', ayahs: 62, revelationType: 'Meccan' },
  { number: 54, nameAr: 'القمر', nameEn: 'Al-Qamar', englishTranslation: 'The Moon', ayahs: 55, revelationType: 'Meccan' },
  { number: 55, nameAr: 'الرحمن', nameEn: 'Ar-Rahman', englishTranslation: 'The Most Merciful', ayahs: 78, revelationType: 'Medinan' },
  { number: 56, nameAr: 'الواقعة', nameEn: 'Al-Waqi\'ah', englishTranslation: 'The Inevitable', ayahs: 96, revelationType: 'Meccan' },
  { number: 57, nameAr: 'الحديد', nameEn: 'Al-Hadid', englishTranslation: 'The Iron', ayahs: 29, revelationType: 'Medinan' },
  { number: 58, nameAr: 'المجادلة', nameEn: 'Al-Mujadila', englishTranslation: 'The Pleading Woman', ayahs: 22, revelationType: 'Medinan' },
  { number: 59, nameAr: 'الحشر', nameEn: 'Al-Hashr', englishTranslation: 'The Exile', ayahs: 24, revelationType: 'Medinan' },
  { number: 60, nameAr: 'الممتحنة', nameEn: 'Al-Mumtahina', englishTranslation: 'She That is Examined', ayahs: 13, revelationType: 'Medinan' },
  { number: 61, nameAr: 'الصف', nameEn: 'As-Saff', englishTranslation: 'The Ranks', ayahs: 14, revelationType: 'Medinan' },
  { number: 62, nameAr: 'الجمعة', nameEn: 'Al-Jumu\'ah', englishTranslation: 'The Congregation', ayahs: 11, revelationType: 'Medinan' },
  { number: 63, nameAr: 'المنافقون', nameEn: 'Al-Munafiqun', englishTranslation: 'The Hypocrites', ayahs: 11, revelationType: 'Medinan' },
  { number: 64, nameAr: 'التغابن', nameEn: 'At-Taghabun', englishTranslation: 'The Mutual Disillusion', ayahs: 18, revelationType: 'Medinan' },
  { number: 65, nameAr: 'الطلاق', nameEn: 'At-Talaq', englishTranslation: 'The Divorce', ayahs: 12, revelationType: 'Medinan' },
  { number: 66, nameAr: 'التحريم', nameEn: 'At-Tahrim', englishTranslation: 'The Prohibiting', ayahs: 12, revelationType: 'Medinan' },
  { number: 67, nameAr: 'الملك', nameEn: 'Al-Mulk', englishTranslation: 'The Sovereignty', ayahs: 30, revelationType: 'Meccan' },
  { number: 68, nameAr: 'القلم', nameEn: 'Al-Qalam', englishTranslation: 'The Pen', ayahs: 52, revelationType: 'Meccan' },
  { number: 69, nameAr: 'الحاقة', nameEn: 'Al-Haqqah', englishTranslation: 'The Reality', ayahs: 52, revelationType: 'Meccan' },
  { number: 70, nameAr: 'المعارج', nameEn: 'Al-Ma\'arij', englishTranslation: 'The Ascending Stairways', ayahs: 44, revelationType: 'Meccan' },
  { number: 71, nameAr: 'نوح', nameEn: 'Nuh', englishTranslation: 'Noah', ayahs: 28, revelationType: 'Meccan' },
  { number: 72, nameAr: 'الجن', nameEn: 'Al-Jinn', englishTranslation: 'The Jinn', ayahs: 28, revelationType: 'Meccan' },
  { number: 73, nameAr: 'المزمل', nameEn: 'Al-Muzzammil', englishTranslation: 'The Enshrouded One', ayahs: 20, revelationType: 'Meccan' },
  { number: 74, nameAr: 'المدثر', nameEn: 'Al-Muddathir', englishTranslation: 'The Cloaked One', ayahs: 56, revelationType: 'Meccan' },
  { number: 75, nameAr: 'القيامة', nameEn: 'Al-Qiyamah', englishTranslation: 'The Resurrection', ayahs: 40, revelationType: 'Meccan' },
  { number: 76, nameAr: 'الإنسان', nameEn: 'Al-Insan', englishTranslation: 'The Human', ayahs: 31, revelationType: 'Medinan' },
  { number: 77, nameAr: 'المرسلات', nameEn: 'Al-Mursalat', englishTranslation: 'The Emissaries', ayahs: 50, revelationType: 'Meccan' },
  { number: 78, nameAr: 'النبأ', nameEn: 'An-Naba', englishTranslation: 'The Tidings', ayahs: 40, revelationType: 'Meccan' },
  { number: 79, nameAr: 'النازعات', nameEn: 'An-Nazi\'at', englishTranslation: 'Those Who Drag Forth', ayahs: 46, revelationType: 'Meccan' },
  { number: 80, nameAr: 'عبس', nameEn: 'Abasa', englishTranslation: 'He Frowned', ayahs: 42, revelationType: 'Meccan' },
  { number: 81, nameAr: 'التكوير', nameEn: 'At-Takwir', englishTranslation: 'The Overthrowing', ayahs: 29, revelationType: 'Meccan' },
  { number: 82, nameAr: 'الانفطار', nameEn: 'Al-Infitar', englishTranslation: 'The Cleaving', ayahs: 19, revelationType: 'Meccan' },
  { number: 83, nameAr: 'المطففين', nameEn: 'Al-Mutaffifin', englishTranslation: 'The Defrauding', ayahs: 36, revelationType: 'Meccan' },
  { number: 84, nameAr: 'الانشقاق', nameEn: 'Al-Inshiqaq', englishTranslation: 'The Sundering', ayahs: 25, revelationType: 'Meccan' },
  { number: 85, nameAr: 'البروج', nameEn: 'Al-Buruj', englishTranslation: 'The Mansions of the Stars', ayahs: 22, revelationType: 'Meccan' },
  { number: 86, nameAr: 'الطارق', nameEn: 'At-Tariq', englishTranslation: 'The Morning Star', ayahs: 17, revelationType: 'Meccan' },
  { number: 87, nameAr: 'الأعلى', nameEn: 'Al-A\'la', englishTranslation: 'The Most High', ayahs: 19, revelationType: 'Meccan' },
  { number: 88, nameAr: 'الغاشية', nameEn: 'Al-Ghashiyah', englishTranslation: 'The Overwhelming', ayahs: 26, revelationType: 'Meccan' },
  { number: 89, nameAr: 'الفجر', nameEn: 'Al-Fajr', englishTranslation: 'The Dawn', ayahs: 30, revelationType: 'Meccan' },
  { number: 90, nameAr: 'البلد', nameEn: 'Al-Balad', englishTranslation: 'The City', ayahs: 20, revelationType: 'Meccan' },
  { number: 91, nameAr: 'الشمس', nameEn: 'Ash-Shams', englishTranslation: 'The Sun', ayahs: 15, revelationType: 'Meccan' },
  { number: 92, nameAr: 'الليل', nameEn: 'Al-Layl', englishTranslation: 'The Night', ayahs: 21, revelationType: 'Meccan' },
  { number: 93, nameAr: 'الضحى', nameEn: 'Ad-Duha', englishTranslation: 'The Morning Hours', ayahs: 11, revelationType: 'Meccan' },
  { number: 94, nameAr: 'الشرح', nameEn: 'Ash-Sharh', englishTranslation: 'The Relief', ayahs: 8, revelationType: 'Meccan' },
  { number: 95, nameAr: 'التين', nameEn: 'At-Tin', englishTranslation: 'The Fig', ayahs: 8, revelationType: 'Meccan' },
  { number: 96, nameAr: 'العلق', nameEn: 'Al-Alaq', englishTranslation: 'The Clot', ayahs: 19, revelationType: 'Meccan' },
  { number: 97, nameAr: 'القدر', nameEn: 'Al-Qadr', englishTranslation: 'The Power', ayahs: 5, revelationType: 'Meccan' },
  { number: 98, nameAr: 'البينة', nameEn: 'Al-Bayyinah', englishTranslation: 'The Clear Proof', ayahs: 8, revelationType: 'Medinan' },
  { number: 99, nameAr: 'الزلزلة', nameEn: 'Az-Zalzalah', englishTranslation: 'The Earthquake', ayahs: 8, revelationType: 'Medinan' },
  { number: 100, nameAr: 'العاديات', nameEn: 'Al-Adiyat', englishTranslation: 'The Courser', ayahs: 11, revelationType: 'Meccan' },
  { number: 101, nameAr: 'القارعة', nameEn: 'Al-Qari\'ah', englishTranslation: 'The Calamity', ayahs: 11, revelationType: 'Meccan' },
  { number: 102, nameAr: 'التكاثر', nameEn: 'At-Takathur', englishTranslation: 'The Rivalry', ayahs: 8, revelationType: 'Meccan' },
  { number: 103, nameAr: 'العصر', nameEn: 'Al-Asr', englishTranslation: 'The Declining Day', ayahs: 3, revelationType: 'Meccan' },
  { number: 104, nameAr: 'الهمزة', nameEn: 'Al-Humazah', englishTranslation: 'The Traducer', ayahs: 9, revelationType: 'Meccan' },
  { number: 105, nameAr: 'الفيل', nameEn: 'Al-Fil', englishTranslation: 'The Elephant', ayahs: 5, revelationType: 'Meccan' },
  { number: 106, nameAr: 'قريش', nameEn: 'Quraysh', englishTranslation: 'Quraysh', ayahs: 4, revelationType: 'Meccan' },
  { number: 107, nameAr: 'الماعون', nameEn: 'Al-Ma\'un', englishTranslation: 'The Small Kindnesses', ayahs: 7, revelationType: 'Meccan' },
  { number: 108, nameAr: 'الكوثر', nameEn: 'Al-Kawthar', englishTranslation: 'The Abundance', ayahs: 3, revelationType: 'Meccan' },
  { number: 109, nameAr: 'الكافرون', nameEn: 'Al-Kafirun', englishTranslation: 'The Disbelievers', ayahs: 6, revelationType: 'Meccan' },
  { number: 110, nameAr: 'النصر', nameEn: 'An-Nasr', englishTranslation: 'The Divine Support', ayahs: 3, revelationType: 'Medinan' },
  { number: 111, nameAr: 'المسد', nameEn: 'Al-Masad', englishTranslation: 'The Palm Fiber', ayahs: 5, revelationType: 'Meccan' },
  { number: 112, nameAr: 'الإخلاص', nameEn: 'Al-Ikhlas', englishTranslation: 'The Sincerity', ayahs: 4, revelationType: 'Meccan' },
  { number: 113, nameAr: 'الفلق', nameEn: 'Al-Falaq', englishTranslation: 'The Daybreak', ayahs: 5, revelationType: 'Meccan' },
  { number: 114, nameAr: 'الناس', nameEn: 'An-Nas', englishTranslation: 'Mankind', ayahs: 6, revelationType: 'Meccan' },
];
