// Bulgarian Translation
import type { TranslationKeys } from './ar';

export const bg: TranslationKeys = {
  app: { name: 'Islami', tagline: 'Твоят Ислямски Спътник' },
  nav: { home: 'Начало', quran: 'Коран', hadith: 'Хадис', rulings: 'Правила', sound: 'Аудио', counters: 'Броячи', settings: 'Настройки' },
  home: { prayerTimes: 'Времена за Молитва', nextPrayer: 'Следваща Молитва', hijriCalendar: 'Хиджри Календар', today: 'Днес', fajr: 'Фаджр', sunrise: 'Изгрев', dhuhr: 'Зухр', asr: 'Аср', maghrib: 'Магриб', isha: 'Иша' },
  counters: { title: 'Броячи', dhikr: 'Зикр', tasbeeh: 'Тасбих', preparations: 'Подготовки', selectDhikr: 'Изберете Зикр', count: 'Брой', reset: 'Нулиране', target: 'Цел' },
  settings: { title: 'Настройки', theme: 'Тема', light: 'Светла', dark: 'Тъмна', auto: 'Автоматична', primaryColor: 'Основен Цвят', fontSize: 'Размер на Шрифта', fontFamily: 'Шрифт', background: 'Стил на Фона', navPosition: 'Позиция на Навигацията', bottom: 'Долу', right: 'Дясно', left: 'Ляво', borderRadius: 'Радиус на Ъгъла', spacing: 'Разстояние', fontWeight: 'Дебелина на Шрифта', lineHeight: 'Височина на Реда', letterSpacing: 'Разстояние между Буквите', animations: 'Анимации', highContrast: 'Висок Контраст', colorBlind: 'Далтонизъм', reset: 'Нулиране', language: 'Език', selectLanguage: 'Изберете Език' },
  colors: { green: 'Ислямско Зелено', gold: 'Златно', blue: 'Синьо', purple: 'Лилаво', red: 'Червено', teal: 'Синьозелено', orange: 'Оранжево', pink: 'Розово', indigo: 'Индиго', brown: 'Кафяво' },
  fontSizes: { xsmall: 'Много Малък', small: 'Малък', medium: 'Среден', large: 'Голям', xlarge: 'Много Голям', xxlarge: 'Огромен' },
  colorBlind: { none: 'Нормален', protanopia: 'Протанопия', deuteranopia: 'Деутеранопия', tritanopia: 'Тританопия' },
  common: { loading: 'Зареждане...', error: 'Възникна грешка', retry: 'Опитай отново', save: 'Запази', cancel: 'Отказ', confirm: 'Потвърди', back: 'Назад', next: 'Следващ', previous: 'Предишен', search: 'Търси', notFound: 'Не е намерено', comingSoon: 'Очаквайте Скоро' },
  calendar: { year: 'Година', month: 'Месец', sacredMonth: 'Свещен Месец', whiteDays: 'Бели Дни', islamicEvent: 'Ислямско Събитие', currentDay: 'Текущ Ден', upcomingEvents: 'Предстоящи Събития', sacredMonths: 'Свещени Месеци', tapFullCalendar: 'Натиснете за пълен Хиджри календар', gregorianDate: 'Григориански Дата', hijriYear: 'Х', muharram: 'Мухаррам', safar: 'Сафар', rabiAlAwwal: 'Раби ал-Аввал', rabiAlThani: 'Раби ас-Сани', jumadaAlUla: 'Джумада ал-Ула', jumadaAlThani: 'Джумада ас-Сания', rajab: 'Раджаб', shaban: 'Шабан', ramadan: 'Рамадан', shawwal: 'Шаввал', dhuAlQidah: 'Зул-Кида', dhuAlHijjah: 'Зул-Хиджа', monthNum: 'Месец' },
  quran: { title: 'Свещен Коран', searchPlaceholder: 'Търсене на сура или аят...', bookmarks: 'Отметки', lastRead: 'Последно Четено', comingSoon: 'Очаквайте Скоро', contentComingSoon: 'Съдържанието на Корана ще бъде добавено тук' },
  hadith: { title: 'Хадис', searchPlaceholder: 'Търсене на хадис...', sahihBukhari: 'Сахих ал-Бухари', sahihMuslim: 'Сахих Муслим', comingSoon: 'Очаквайте Скоро', contentComingSoon: 'Хадисите на Пророка ﷺ ще бъдат добавени тук' },
  sound: { title: 'Рецитации', selectReciter: 'Изберете Рецитатор', reciters: 'Рецитатори', recitations: 'Рецитации на Корана', murattal: 'Мураттал', mujawwad: 'Муджаввад' },
  rulings: { title: 'Правила', searchPlaceholder: 'Търсене на правило...', prayerRulings: 'Правила за Молитва', fastingRulings: 'Правила за Пост', zakatRulings: 'Правила за Закат', hajjRulings: 'Правила за Хадж', breastfeedingRulings: 'Правила за Кърмене', purificationRulings: 'Правила за Пречистване', comingSoon: 'Очаквайте Скоро' },
  dhikr: { currentDhikr: 'Текущ Зикр', tapToCount: 'Натиснете за Броене', resetCount: 'Нулиране на Брояч', dhikrNotFound: 'Зикр не е намерен', backToSelection: 'Назад към Избор на Зикр', tasbeehah: 'броене', subhanallah: 'СубханАллах', alhamdulillah: 'Алхамдулиллах', allahuakbar: 'Аллаху Акбар', lailaha: 'Ля иляха илляллах', astaghfirullah: 'Астагфируллах', lahawla: 'Ля хавла валя куввата илля биллях', subhanallahwabihamdi: 'СубханАллахи ва бихамдихи', salawat: 'Благословии за Пророка ﷺ', descSubhanallah: 'Прославяне на Аллах', descAlhamdulillah: 'Хвалене на Аллах', descAllahuakbar: 'Величаене на Аллах', descLailaha: 'Изповед на Вярата', descAstaghfirullah: 'Търсене на Прошка', descLahawla: 'Декларация на Доверие', descSubhanallahwabihamdi: 'Две леки думи на езика', descSalawat: 'О Аллах, благослови нашия Пророк Мухаммад' },
  tasbeeh: { title: 'Тасбих Страници', morningAdhkar: 'Сутрешни Азкар', eveningAdhkar: 'Вечерни Азкар', sleepAdhkar: 'Азкар за Сън', variousAdhkar: 'Различни Азкар', adhkarCount: 'азкар', resetAll: 'Нулиране на Всички Броячи', done: 'Готово ✓', morningEveningAdhkar: 'Сутрешни, вечерни и азкар за сън', customizeSettings: 'Персонализиране на цветове, шрифтове и интерфейс' },
  preparations: { title: 'Подготовки', quranLearning: 'Свещен Коран', quranLearningDesc: 'Изучаване на Коран и Таджуид', breastfeedingRulings: 'Правила за Кърмене', breastfeedingDesc: 'Фикх правила за кърмене', threeDContent: '3D Съдържание', threeDDesc: 'Интерактивно образователно съдържание', interactiveMap: 'Интерактивна Карта', interactiveMapDesc: 'Изследвайте ислямския свят', mapInfo: 'Интерактивна карта на ислямския свят с информация за всяка страна ще бъде добавена', comingSoon: 'Очаквайте Скоро' },
  prayerDetail: { prayer: 'Молитва', rakaat: 'Ракаат', fard: 'Задължително', sunnahBefore: 'Сунна Преди', sunnahAfter: 'Сунна След', completed: 'Завършено', required: 'Изисквано', addRakaat: 'Добави Рака', completedLabel: 'Завършено', virtues: 'Добродетели на', resetCount: 'Нулиране на Брояч', prayerNotFound: 'Молитва не е намерена', backToHome: 'Назад към Начало' },
  islamicEvent: {
    practices: 'Препоръчани Практики', duaOrDhikr: 'Дуа или Зикр', quranVerses: 'Аяти от Корана', surah: 'Сура', verse: 'Аят', backToCalendar: 'Назад към Календара', eventNotFound: 'Събитие не е намерено', month: 'Месец', typeHoliday: 'Празник', typeFasting: 'Пост', typeSpecial: 'Специален', typeWorship: 'Поклонение',
    events: {
      newYear: { name: 'Ислямска Нова Година', description: 'Начало на новата Хиджри година', fullDescription: '1-ви Мухаррам бележи началото на новата ислямска година.', practices: ['Размисъл за миналата година и покаяние', 'Поставяне на благочестиви намерения', 'Молитва за добро и благословии'] },
      ashura: { name: 'Ден на Ашура', description: 'Пост на Ашура (препоръчва се и на 9-ти)', fullDescription: 'Ашура е 10-ти Мухаррам, денят когато Аллах спаси Муса и народа му от Фараона.', practices: ['Пост на 9-ти и 10-ти Мухаррам', 'Увеличаване на зикр и дуа', 'Даване на милостиня'] },
      mawlid: { name: 'Рожден Ден на Пророка', description: 'Възпоменание за раждането на Пророка ﷺ', fullDescription: '12-ти Раби ал-Аввал бележи раждането на Пророка Мухаммад ﷺ.', practices: ['Изпращане на обилни благословии за Пророка ﷺ', 'Четене на биографията на Пророка', 'Учене от характера на Пророка ﷺ'] },
      israMiraj: { name: 'Исра и Мирадж', description: 'Благословена и отличена нощ', fullDescription: 'Нощното Пътуване и Възнесението е когато Пророкът ﷺ бе пренесен от Свещената Джамия до Джамията ал-Акса.', practices: ['Изпращане на обилни благословии за Пророка ﷺ', 'Молитва от поне два раката', 'Четене на Сура ал-Исра', 'Размисъл за чудесата на Аллах'] },
      nisfShaban: { name: 'Нощта на Средата на Шабан', description: 'Нощта на промяната на Кибла', fullDescription: 'Нощта на средата на Шабан е благословена нощ когато Кибла бе променена от Йерусалим към Кааба.', practices: ['Увеличаване на дуа и истигфар', 'Молитва кийям ал-лейл', 'Размисъл за историята на промяната на Кибла'] },
      ramadanStart: { name: 'Начало на Рамадан', description: 'Месец на поста и Корана', fullDescription: 'Благословеният месец Рамадан е месец на поста, молитвата и четенето на Корана.', practices: ['Пост през целия месец', 'Четене и завършване на Корана', 'Молитва Таравих', 'Увеличаване на благотворителността'] },
      lastTen: { name: 'Последните Десет Нощи', description: 'Търсене на Лейлат ал-Кадр в нечетните нощи', fullDescription: 'Последните десет нощи на Рамадан съдържат Лейлат ал-Кадр, която е по-добра от хиляда месеца.', practices: ['Молитва кийям в нечетни нощи (21, 23, 25, 27, 29)', 'Извършване на итикаф в джамията', 'Увеличаване на дуа и зикр', 'Рецитиране на Корана'] },
      eidFitr: { name: 'Ейд ал-Фитр', description: 'Радостта на постещия и такбират', fullDescription: 'Ейд ал-Фитр е ден на радост след поста на месец Рамадан.', practices: ['Рецитиране на такбират от нощта на Ейд до молитвата', 'Извършване на молитва Ейд', 'Плащане на Закат ал-Фитр преди молитвата', 'Посещаване на роднини'] },
      arafah: { name: 'Ден на Арафат', description: 'Най-добрият ден за не-поклонници, постът изкупва две години', fullDescription: 'Денят на Арафат е 9-ти Зул-Хиджа, най-добрият ден на който слънцето е изгряло.', practices: ['Пост на Деня на Арафат (за не-поклонници)', 'Увеличаване на зикр и дуа', 'Покаяние и търсене на прошка'] },
      eidAdha: { name: 'Ейд ал-Адха', description: 'Ден на жертвоприношението и дните на Ташрик', fullDescription: 'Ейд ал-Адха е денят на жертвоприношението (10-ти Зул-Хиджа) последван от дните на Ташрик.', practices: ['Рецитиране на такбират през дните на Ташрик', 'Извършване на молитва Ейд', 'Принасяне на жертва', 'Поддържане на семейни връзки'] },
    },
  },
};
