// Danish Translation
import type { TranslationKeys } from './ar';

export const da: TranslationKeys = {
  app: { name: 'Islami', tagline: 'Din Islamiske Ledsager' },
  nav: { home: 'Hjem', quran: 'Koranen', hadith: 'Hadith', rulings: 'Regler', sound: 'Lyd', counters: 'Tællere', settings: 'Indstillinger' },
  home: { prayerTimes: 'Bønnetider', nextPrayer: 'Næste Bøn', hijriCalendar: 'Hijrikalender', today: 'I dag', fajr: 'Fajr', sunrise: 'Solopgang', dhuhr: 'Dhuhr', asr: 'Asr', maghrib: 'Maghrib', isha: 'Isha' },
  counters: { title: 'Tællere', dhikr: 'Dhikr', tasbeeh: 'Tasbeeh', preparations: 'Forberedelser', selectDhikr: 'Vælg Dhikr', count: 'Tæl', reset: 'Nulstil', target: 'Mål' },
  settings: { title: 'Indstillinger', theme: 'Tema', light: 'Lyst', dark: 'Mørkt', auto: 'Automatisk', primaryColor: 'Primærfarve', fontSize: 'Skriftstørrelse', fontFamily: 'Skrifttype', background: 'Baggrundsstil', navPosition: 'Navigationsposition', bottom: 'Bund', right: 'Højre', left: 'Venstre', borderRadius: 'Hjørneradius', spacing: 'Afstand', fontWeight: 'Skrifttykkelse', lineHeight: 'Linjehøjde', letterSpacing: 'Bogstavafstand', animations: 'Animationer', highContrast: 'Høj Kontrast', colorBlind: 'Farveblindhed', reset: 'Nulstil', language: 'Sprog', selectLanguage: 'Vælg Sprog' },
  colors: { green: 'Islamisk Grøn', gold: 'Guld', blue: 'Blå', purple: 'Lilla', red: 'Rød', teal: 'Blågrøn', orange: 'Orange', pink: 'Pink', indigo: 'Indigo', brown: 'Brun' },
  fontSizes: { xsmall: 'Ekstra Lille', small: 'Lille', medium: 'Medium', large: 'Stor', xlarge: 'Ekstra Stor', xxlarge: 'Enorm' },
  colorBlind: { none: 'Normal', protanopia: 'Protanopi', deuteranopia: 'Deuteranopi', tritanopia: 'Tritanopi' },
  common: { loading: 'Indlæser...', error: 'Der opstod en fejl', retry: 'Prøv igen', save: 'Gem', cancel: 'Annuller', confirm: 'Bekræft', back: 'Tilbage', next: 'Næste', previous: 'Forrige', search: 'Søg', notFound: 'Ikke Fundet', comingSoon: 'Kommer Snart' },
  calendar: { year: 'År', month: 'Måned', sacredMonth: 'Hellig Måned', whiteDays: 'Hvide Dage', islamicEvent: 'Islamisk Begivenhed', currentDay: 'Aktuel Dag', upcomingEvents: 'Kommende Begivenheder', sacredMonths: 'Hellige Måneder', tapFullCalendar: 'Tryk for fuld Hijrikalender', gregorianDate: 'Gregoriansk Dato', hijriYear: 'H', muharram: 'Muharram', safar: 'Safar', rabiAlAwwal: 'Rabi al-Awwal', rabiAlThani: 'Rabi al-Thani', jumadaAlUla: 'Jumada al-Ula', jumadaAlThani: 'Jumada al-Thani', rajab: 'Rajab', shaban: 'Sha\'ban', ramadan: 'Ramadan', shawwal: 'Shawwal', dhuAlQidah: 'Dhul-Qi\'dah', dhuAlHijjah: 'Dhul-Hijjah', monthNum: 'Måned' },
  quran: { title: 'Hellige Koran', searchPlaceholder: 'Søg efter en sura eller vers...', bookmarks: 'Bogmærker', lastRead: 'Sidst Læst', comingSoon: 'Kommer Snart', contentComingSoon: 'Koranindhold tilføjes her' },
  hadith: { title: 'Hadith', searchPlaceholder: 'Søg efter en hadith...', sahihBukhari: 'Sahih al-Bukhari', sahihMuslim: 'Sahih Muslim', comingSoon: 'Kommer Snart', contentComingSoon: 'Profetens ﷺ hadither tilføjes her' },
  sound: { title: 'Recitationer', selectReciter: 'Vælg Recitator', reciters: 'Recitatorer', recitations: 'Koranrecitationer', murattal: 'Murattal', mujawwad: 'Mujawwad' },
  rulings: { title: 'Regler', searchPlaceholder: 'Søg efter en regel...', prayerRulings: 'Bønneregler', fastingRulings: 'Fasteregler', zakatRulings: 'Zakatregler', hajjRulings: 'Hajjregler', breastfeedingRulings: 'Ammeregler', purificationRulings: 'Renselsesregler', comingSoon: 'Kommer Snart' },
  dhikr: { currentDhikr: 'Aktuel Dhikr', tapToCount: 'Tryk for at Tælle', resetCount: 'Nulstil Tæller', dhikrNotFound: 'Dhikr ikke fundet', backToSelection: 'Tilbage til Dhikr-valg', tasbeehah: 'tælling', subhanallah: 'SubhanAllah', alhamdulillah: 'Alhamdulillah', allahuakbar: 'Allahu Akbar', lailaha: 'La ilaha illallah', astaghfirullah: 'Astaghfirullah', lahawla: 'La hawla wala quwwata illa billah', subhanallahwabihamdi: 'SubhanAllahi wa bihamdihi', salawat: 'Velsignelser over Profeten ﷺ', descSubhanallah: 'Forherlige Allah', descAlhamdulillah: 'Prise Allah', descAllahuakbar: 'Forstørre Allah', descLailaha: 'Trosbekendelse', descAstaghfirullah: 'Søge Tilgivelse', descLahawla: 'Erklæring om Tillid', descSubhanallahwabihamdi: 'To lette ord på tungen', descSalawat: 'O Allah, velsign vores Profet Muhammad' },
  tasbeeh: { title: 'Tasbeeh-sider', morningAdhkar: 'Morgen-Adhkar', eveningAdhkar: 'Aften-Adhkar', sleepAdhkar: 'Søvn-Adhkar', variousAdhkar: 'Diverse Adhkar', adhkarCount: 'adhkar', resetAll: 'Nulstil Alle Tællere', done: 'Færdig ✓', morningEveningAdhkar: 'Morgen-, aften- og søvn-adhkar', customizeSettings: 'Tilpas farver, skrifttyper og grænseflade' },
  preparations: { title: 'Forberedelser', quranLearning: 'Hellige Koran', quranLearningDesc: 'Lær Koranen og Tajwid', breastfeedingRulings: 'Ammeregler', breastfeedingDesc: 'Fiqh-regler om amning', threeDContent: '3D-indhold', threeDDesc: 'Interaktivt uddannelsesindhold', interactiveMap: 'Interaktivt Kort', interactiveMapDesc: 'Udforsk den islamiske verden', mapInfo: 'Et interaktivt kort over den islamiske verden med information om hvert land tilføjes', comingSoon: 'Kommer Snart' },
  prayerDetail: { prayer: 'Bøn', rakaat: 'Rakaat', fard: 'Obligatorisk', sunnahBefore: 'Sunnah Før', sunnahAfter: 'Sunnah Efter', completed: 'Fuldført', required: 'Påkrævet', addRakaat: 'Tilføj Raka', completedLabel: 'Fuldført', virtues: 'Dyder af', resetCount: 'Nulstil Tæller', prayerNotFound: 'Bøn ikke fundet', backToHome: 'Tilbage til Hjem' },
  islamicEvent: {
    practices: 'Anbefalede Praksisser', duaOrDhikr: 'Dua eller Dhikr', quranVerses: 'Koranvers', surah: 'Sura', verse: 'Vers', backToCalendar: 'Tilbage til Kalenderen', eventNotFound: 'Begivenhed ikke fundet', month: 'Måned', typeHoliday: 'Højtid', typeFasting: 'Faste', typeSpecial: 'Speciel', typeWorship: 'Tilbedelse',
    events: {
      newYear: { name: 'Islamisk Nytår', description: 'Begyndelsen af det nye Hijriår', fullDescription: 'Den 1. Muharram markerer begyndelsen af det nye islamiske år, til minde om Profetens ﷺ Hijra fra Mekka til Medina.', practices: ['Reflektere over det forgangne år og angre', 'Sætte fromme intentioner for det nye år', 'Bede om godhed og velsignelser'] },
      ashura: { name: 'Ashura-dagen', description: 'Faste på Ashura (anbefalet at faste den 9. også)', fullDescription: 'Ashura er den 10. Muharram, dagen da Allah reddede Musa og hans folk fra Farao.', practices: ['Faste den 9. og 10. Muharram', 'Øge dhikr og dua', 'Give almisser'] },
      mawlid: { name: 'Profetens Fødselsdag', description: 'Højtideligholdelse af Profetens ﷺ fødsel', fullDescription: 'Den 12. Rabi al-Awwal markerer Profeten Muhammads ﷺ fødsel.', practices: ['Sende rigelige velsignelser over Profeten ﷺ', 'Læse Profetens biografi', 'Lære af Profetens ﷺ karakter'] },
      israMiraj: { name: 'Isra og Mi\'raj', description: 'En velsignet og fremragende nat', fullDescription: 'Nattrejsen og Himmelfarten er da Profeten ﷺ blev ført fra den Hellige Moské til al-Aqsa Moskeen.', practices: ['Sende rigelige velsignelser over Profeten ﷺ', 'Bede mindst to rakat', 'Læse Sura al-Isra', 'Reflektere over Allahs undere'] },
      nisfShaban: { name: 'Midt i Sha\'ban-natten', description: 'Natten for Qibla-ændringen', fullDescription: 'Natten midt i Sha\'ban er en velsignet nat da Qibla blev ændret fra Jerusalem til Kaaba.', practices: ['Øge dua og istighfar', 'Bede qiyam al-layl', 'Reflektere over Qibla-ændringens historie'] },
      ramadanStart: { name: 'Ramadans Begyndelse', description: 'Fastens og Koranens måned', fullDescription: 'Den velsignede Ramadan-måned er fastens, bønnens og Koranrecitationens måned.', practices: ['Faste hele måneden', 'Læse og fuldføre Koranen', 'Bede Tarawih', 'Øge velgørenhed'] },
      lastTen: { name: 'Sidste Ti Nætter', description: 'Søge Laylat al-Qadr i ulige nætter', fullDescription: 'De sidste ti nætter af Ramadan indeholder Laylat al-Qadr, som er bedre end tusind måneder.', practices: ['Bede qiyam i ulige nætter (21, 23, 25, 27, 29)', 'Udføre i\'tikaf i moskeen', 'Øge dua og dhikr', 'Recitere Koranen'] },
      eidFitr: { name: 'Eid al-Fitr', description: 'Den fastendes glæde og takbirat', fullDescription: 'Eid al-Fitr er glædens dag efter Ramadans faste.', practices: ['Recitere takbirat fra Eid-natten til Eid-bønnen', 'Udføre Eid-bønnen', 'Betale Zakat al-Fitr før bønnen', 'Besøge slægtninge'] },
      arafah: { name: 'Arafat-dagen', description: 'Bedste dag for ikke-pilgrimme, faste soner to år', fullDescription: 'Arafat-dagen er den 9. Dhul Hijjah, den bedste dag solen er stået op på.', practices: ['Faste på Arafat-dagen (for ikke-pilgrimme)', 'Øge dhikr og dua', 'Angre og søge tilgivelse'] },
      eidAdha: { name: 'Eid al-Adha', description: 'Offerdagen og Tashriq-dagene', fullDescription: 'Eid al-Adha er offerdagen (10. Dhul Hijjah) fulgt af Tashriq-dagene.', practices: ['Recitere takbirat under Tashriq-dagene', 'Udføre Eid-bønnen', 'Ofre dyret', 'Opretholde familiebånd'] },
    },
  },
};
