// Greek Translation
import type { TranslationKeys } from './ar';

export const el: TranslationKeys = {
  app: { name: 'Islami', tagline: 'Ο Ισλαμικός Σύντροφός Σου' },
  nav: { home: 'Αρχική', quran: 'Κοράνι', hadith: 'Χαντίθ', rulings: 'Κανόνες', sound: 'Ήχος', counters: 'Μετρητές', settings: 'Ρυθμίσεις' },
  home: { prayerTimes: 'Ώρες Προσευχής', nextPrayer: 'Επόμενη Προσευχή', hijriCalendar: 'Ημερολόγιο Χίτζρα', today: 'Σήμερα', fajr: 'Φατζρ', sunrise: 'Ανατολή', dhuhr: 'Ζουχρ', asr: 'Ασρ', maghrib: 'Μαγκρίμπ', isha: 'Ισά' },
  counters: { title: 'Μετρητές', dhikr: 'Ζικρ', tasbeeh: 'Τασμπίχ', preparations: 'Προετοιμασίες', selectDhikr: 'Επιλογή Ζικρ', count: 'Μέτρηση', reset: 'Επαναφορά', target: 'Στόχος' },
  settings: { title: 'Ρυθμίσεις', theme: 'Θέμα', light: 'Φωτεινό', dark: 'Σκοτεινό', auto: 'Αυτόματο', primaryColor: 'Κύριο Χρώμα', fontSize: 'Μέγεθος Γραμματοσειράς', fontFamily: 'Γραμματοσειρά', background: 'Στυλ Φόντου', navPosition: 'Θέση Πλοήγησης', bottom: 'Κάτω', right: 'Δεξιά', left: 'Αριστερά', borderRadius: 'Ακτίνα Γωνίας', spacing: 'Απόσταση', fontWeight: 'Βάρος Γραμματοσειράς', lineHeight: 'Ύψος Γραμμής', letterSpacing: 'Απόσταση Γραμμάτων', animations: 'Κινούμενα Σχέδια', highContrast: 'Υψηλή Αντίθεση', colorBlind: 'Αχρωματοψία', reset: 'Επαναφορά', language: 'Γλώσσα', selectLanguage: 'Επιλογή Γλώσσας' },
  colors: { green: 'Ισλαμικό Πράσινο', gold: 'Χρυσό', blue: 'Μπλε', purple: 'Μοβ', red: 'Κόκκινο', teal: 'Γαλαζοπράσινο', orange: 'Πορτοκαλί', pink: 'Ροζ', indigo: 'Λουλακί', brown: 'Καφέ' },
  fontSizes: { xsmall: 'Πολύ Μικρό', small: 'Μικρό', medium: 'Μεσαίο', large: 'Μεγάλο', xlarge: 'Πολύ Μεγάλο', xxlarge: 'Τεράστιο' },
  colorBlind: { none: 'Κανονικό', protanopia: 'Πρωτανοπία', deuteranopia: 'Δευτερανοπία', tritanopia: 'Τριτανοπία' },
  common: { loading: 'Φόρτωση...', error: 'Παρουσιάστηκε σφάλμα', retry: 'Επανάληψη', save: 'Αποθήκευση', cancel: 'Ακύρωση', confirm: 'Επιβεβαίωση', back: 'Πίσω', next: 'Επόμενο', previous: 'Προηγούμενο', search: 'Αναζήτηση', notFound: 'Δεν Βρέθηκε', comingSoon: 'Σύντομα' },
  calendar: { year: 'Έτος', month: 'Μήνας', sacredMonth: 'Ιερός Μήνας', whiteDays: 'Λευκές Ημέρες', islamicEvent: 'Ισλαμικό Γεγονός', currentDay: 'Τρέχουσα Ημέρα', upcomingEvents: 'Επερχόμενα Γεγονότα', sacredMonths: 'Ιεροί Μήνες', tapFullCalendar: 'Πατήστε για πλήρες ημερολόγιο Χίτζρα', gregorianDate: 'Γρηγοριανή Ημερομηνία', hijriYear: 'Μ.Χ.', muharram: 'Μουχαρράμ', safar: 'Σαφάρ', rabiAlAwwal: 'Ραμπί αλ-Αούαλ', rabiAlThani: 'Ραμπί αθ-Θανί', jumadaAlUla: 'Τζουμάντα αλ-Ούλα', jumadaAlThani: 'Τζουμάντα αθ-Θανίγια', rajab: 'Ρατζάμπ', shaban: 'Σαμπάν', ramadan: 'Ραμαντάν', shawwal: 'Σαουάλ', dhuAlQidah: 'Ζουλ-Κίντα', dhuAlHijjah: 'Ζουλ-Χίτζα', monthNum: 'Μήνας' },
  quran: { title: 'Ιερό Κοράνι', searchPlaceholder: 'Αναζήτηση σούρας ή εδαφίου...', bookmarks: 'Σελιδοδείκτες', lastRead: 'Τελευταία Ανάγνωση', comingSoon: 'Σύντομα', contentComingSoon: 'Το περιεχόμενο του Κορανίου θα προστεθεί εδώ', collections: 'Συλλογές', selectCollection: 'Επιλέξτε συλλογή', sections: 'Κεφάλαια', selectSection: 'Επιλέξτε κεφάλαιο', hadithNumber: 'Χάντιθ №', arabicText: 'Αραβικό κείμενο', translation: 'Μετάφραση', loadingHadiths: 'Φόρτωση χάντιθ...', errorLoading: 'Σφάλμα κατά τη φόρτωση', noHadiths: 'Δεν υπάρχουν χάντιθ σε αυτό το κεφάλαιο', totalHadiths: 'Σύνολο χάντιθ', allCollections: 'Όλες οι συλλογές', backToCollections: 'Επιστροφή στις συλλογές', backToSections: 'Επιστροφή στα κεφάλαια' },
  hadith: { title: 'Χαντίθ', searchPlaceholder: 'Αναζήτηση χαντίθ...', sahihBukhari: 'Σαχίχ αλ-Μπουχάρι', sahihMuslim: 'Σαχίχ Μούσλιμ', comingSoon: 'Σύντομα', contentComingSoon: 'Τα χαντίθ του Προφήτη ﷺ θα προστεθούν εδώ' },
  sound: { title: 'Απαγγελίες', selectReciter: 'Επιλογή Απαγγελέα', reciters: 'Απαγγελείς', recitations: 'Απαγγελίες Κορανίου', murattal: 'Μουράτταλ', mujawwad: 'Μουτζάουαντ' },
  rulings: { title: 'Κανόνες', searchPlaceholder: 'Αναζήτηση κανόνα...', prayerRulings: 'Κανόνες Προσευχής', fastingRulings: 'Κανόνες Νηστείας', zakatRulings: 'Κανόνες Ζακάτ', hajjRulings: 'Κανόνες Χατζ', breastfeedingRulings: 'Κανόνες Θηλασμού', purificationRulings: 'Κανόνες Καθαρισμού', comingSoon: 'Σύντομα' },
  dhikr: { currentDhikr: 'Τρέχον Ζικρ', tapToCount: 'Πατήστε για Μέτρηση', resetCount: 'Επαναφορά Μετρητή', dhikrNotFound: 'Ζικρ δεν βρέθηκε', backToSelection: 'Πίσω στην Επιλογή Ζικρ', tasbeehah: 'μέτρηση', subhanallah: 'ΣουμπχανΑλλάχ', alhamdulillah: 'Αλχαμντουλιλλάχ', allahuakbar: 'Αλλάχου Άκμπαρ', lailaha: 'Λα ιλάχα ιλλαλλάχ', astaghfirullah: 'Ασταγκφιρουλλάχ', lahawla: 'Λα χάουλα ουαλά κουούατα ιλλά μπιλλάχ', subhanallahwabihamdi: 'ΣουμπχανΑλλάχι ουα μπιχαμντίχι', salawat: 'Ευλογίες στον Προφήτη ﷺ', descSubhanallah: 'Δοξολόγηση του Αλλάχ', descAlhamdulillah: 'Αίνεση του Αλλάχ', descAllahuakbar: 'Μεγαλοποίηση του Αλλάχ', descLailaha: 'Ομολογία Πίστης', descAstaghfirullah: 'Αναζήτηση Συγχώρεσης', descLahawla: 'Δήλωση Εμπιστοσύνης', descSubhanallahwabihamdi: 'Δύο ελαφριές λέξεις στη γλώσσα', descSalawat: 'Ω Αλλάχ, ευλόγησε τον Προφήτη μας Μουχάμμαντ' },
  tasbeeh: { title: 'Σελίδες Τασμπίχ', morningAdhkar: 'Πρωινά Αζκάρ', eveningAdhkar: 'Βραδινά Αζκάρ', sleepAdhkar: 'Αζκάρ Ύπνου', variousAdhkar: 'Διάφορα Αζκάρ', adhkarCount: 'αζκάρ', resetAll: 'Επαναφορά Όλων', done: 'Έγινε ✓', morningEveningAdhkar: 'Πρωινά, βραδινά και αζκάρ ύπνου', customizeSettings: 'Προσαρμογή χρωμάτων, γραμματοσειρών και διεπαφής' },
  preparations: { title: 'Προετοιμασίες', quranLearning: 'Ιερό Κοράνι', quranLearningDesc: 'Εκμάθηση Κορανίου και Ταζουίντ', breastfeedingRulings: 'Κανόνες Θηλασμού', breastfeedingDesc: 'Κανόνες φικχ για θηλασμό', threeDContent: '3D Περιεχόμενο', threeDDesc: 'Διαδραστικό εκπαιδευτικό περιεχόμενο', interactiveMap: 'Διαδραστικός Χάρτης', interactiveMapDesc: 'Εξερευνήστε τον ισλαμικό κόσμο', mapInfo: 'Θα προστεθεί διαδραστικός χάρτης του ισλαμικού κόσμου', comingSoon: 'Σύντομα' },
  prayerDetail: { prayer: 'Προσευχή', rakaat: 'Ρακαάτ', fard: 'Υποχρεωτικό', sunnahBefore: 'Σούννα Πριν', sunnahAfter: 'Σούννα Μετά', completed: 'Ολοκληρώθηκε', required: 'Απαιτούμενο', addRakaat: 'Προσθήκη Ράκα', completedLabel: 'Ολοκληρώθηκε', virtues: 'Αρετές', resetCount: 'Επαναφορά Μετρητή', prayerNotFound: 'Προσευχή δεν βρέθηκε', backToHome: 'Πίσω στην Αρχική' },
  islamicEvent: {
    practices: 'Συνιστώμενες Πρακτικές', duaOrDhikr: 'Ντουά ή Ζικρ', quranVerses: 'Εδάφια Κορανίου', surah: 'Σούρα', verse: 'Εδάφιο', backToCalendar: 'Πίσω στο Ημερολόγιο', eventNotFound: 'Γεγονός δεν βρέθηκε', month: 'Μήνας', typeHoliday: 'Γιορτή', typeFasting: 'Νηστεία', typeSpecial: 'Ειδικό', typeWorship: 'Λατρεία',
    events: {
      newYear: { name: 'Ισλαμική Πρωτοχρονιά', description: 'Αρχή του νέου έτους Χίτζρα', fullDescription: 'Η 1η Μουχαρράμ σημαδεύει την αρχή του νέου ισλαμικού έτους.', practices: ['Αναλογισμός του περασμένου έτους και μετάνοια', 'Ευσεβείς προθέσεις για το νέο έτος', 'Προσευχή για καλοσύνη και ευλογίες'] },
      ashura: { name: 'Ημέρα Ασούρα', description: 'Νηστεία Ασούρα (συνιστάται και στις 9)', fullDescription: 'Η Ασούρα είναι η 10η Μουχαρράμ, η ημέρα που ο Αλλάχ έσωσε τον Μούσα και τον λαό του.', practices: ['Νηστεία 9η και 10η Μουχαρράμ', 'Αύξηση ζικρ και ντουά', 'Ελεημοσύνη'] },
      mawlid: { name: 'Γενέθλια του Προφήτη', description: 'Μνήμη γέννησης του Προφήτη ﷺ', fullDescription: 'Η 12η Ραμπί αλ-Αούαλ σημαδεύει τη γέννηση του Προφήτη Μουχάμμαντ ﷺ.', practices: ['Άφθονες ευλογίες στον Προφήτη ﷺ', 'Ανάγνωση βιογραφίας του Προφήτη', 'Μάθηση από τον χαρακτήρα του Προφήτη ﷺ'] },
      israMiraj: { name: 'Ισρά και Μιράτζ', description: 'Ευλογημένη και ξεχωριστή νύχτα', fullDescription: 'Το Νυχτερινό Ταξίδι και η Ανάληψη είναι όταν ο Προφήτης ﷺ μεταφέρθηκε από το Ιερό Τζαμί στο Τζαμί αλ-Άκσα.', practices: ['Άφθονες ευλογίες στον Προφήτη ﷺ', 'Τουλάχιστον δύο ρακάτ προσευχής', 'Ανάγνωση Σούρα αλ-Ισρά', 'Αναλογισμός θαυμάτων του Αλλάχ'] },
      nisfShaban: { name: 'Νύχτα Μέσου Σαμπάν', description: 'Νύχτα αλλαγής Κίμπλα', fullDescription: 'Η νύχτα μέσου Σαμπάν είναι ευλογημένη νύχτα όταν η Κίμπλα άλλαξε από την Ιερουσαλήμ στην Κάαμπα.', practices: ['Αύξηση ντουά και ιστιγκφάρ', 'Προσευχή κιγιάμ αλ-λέιλ', 'Αναλογισμός ιστορίας αλλαγής Κίμπλα'] },
      ramadanStart: { name: 'Αρχή Ραμαντάν', description: 'Μήνας νηστείας και Κορανίου', fullDescription: 'Ο ευλογημένος μήνας Ραμαντάν είναι ο μήνας νηστείας, προσευχής και ανάγνωσης Κορανίου.', practices: ['Νηστεία ολόκληρο τον μήνα', 'Ανάγνωση και ολοκλήρωση Κορανίου', 'Προσευχή Ταραουίχ', 'Αύξηση φιλανθρωπίας'] },
      lastTen: { name: 'Τελευταίες Δέκα Νύχτες', description: 'Αναζήτηση Λέιλατ αλ-Κάντρ σε μονές νύχτες', fullDescription: 'Οι τελευταίες δέκα νύχτες περιέχουν Λέιλατ αλ-Κάντρ, καλύτερη από χίλιους μήνες.', practices: ['Κιγιάμ σε μονές νύχτες (21, 23, 25, 27, 29)', 'Ιτικάφ στο τζαμί', 'Αύξηση ντουά και ζικρ', 'Απαγγελία Κορανίου'] },
      eidFitr: { name: 'Ίντ αλ-Φιτρ', description: 'Χαρά του νηστευτή και τακμπιράτ', fullDescription: 'Η Ίντ αλ-Φιτρ είναι η ημέρα χαράς μετά τη νηστεία του Ραμαντάν.', practices: ['Τακμπιράτ από τη νύχτα Ίντ ως την προσευχή', 'Προσευχή Ίντ', 'Πληρωμή Ζακάτ αλ-Φιτρ πριν την προσευχή', 'Επίσκεψη συγγενών'] },
      arafah: { name: 'Ημέρα Αραφάτ', description: 'Καλύτερη ημέρα για μη προσκυνητές', fullDescription: 'Η Ημέρα Αραφάτ είναι η 9η Ζουλ-Χίτζα, η καλύτερη ημέρα που ανέτειλε ο ήλιος.', practices: ['Νηστεία Ημέρα Αραφάτ (μη προσκυνητές)', 'Αύξηση ζικρ και ντουά', 'Μετάνοια και αναζήτηση συγχώρεσης'] },
      eidAdha: { name: 'Ίντ αλ-Άντχα', description: 'Ημέρα θυσίας και ημέρες Τασρίκ', fullDescription: 'Η Ίντ αλ-Άντχα είναι η ημέρα θυσίας (10η Ζουλ-Χίτζα).', practices: ['Τακμπιράτ κατά τις ημέρες Τασρίκ', 'Προσευχή Ίντ', 'Θυσία', 'Διατήρηση οικογενειακών δεσμών'] },
    },
  },
};
