// Hungarian Translation
import type { TranslationKeys } from './ar';

export const hu: TranslationKeys = {
  app: { name: 'Islami', tagline: 'Iszlám Társad' },
  nav: { home: 'Főoldal', quran: 'Korán', hadith: 'Hadísz', rulings: 'Szabályok', sound: 'Hang', counters: 'Számlálók', settings: 'Beállítások' },
  home: { prayerTimes: 'Imaidők', nextPrayer: 'Következő Ima', hijriCalendar: 'Hidzsri Naptár', today: 'Ma', fajr: 'Fadzsr', sunrise: 'Napkelte', dhuhr: 'Dhuhr', asr: 'Aszr', maghrib: 'Magrib', isha: 'Isá' },
  counters: { title: 'Számlálók', dhikr: 'Dhikr', tasbeeh: 'Taszbeeh', preparations: 'Előkészületek', selectDhikr: 'Dhikr Kiválasztása', count: 'Számolás', reset: 'Visszaállítás', target: 'Cél' },
  settings: { title: 'Beállítások', theme: 'Téma', light: 'Világos', dark: 'Sötét', auto: 'Automatikus', primaryColor: 'Elsődleges Szín', fontSize: 'Betűméret', fontFamily: 'Betűtípus', background: 'Háttérstílus', navPosition: 'Navigáció Helyzete', bottom: 'Alsó', right: 'Jobb', left: 'Bal', borderRadius: 'Sarokrádiusz', spacing: 'Térköz', fontWeight: 'Betűvastagság', lineHeight: 'Sormagasság', letterSpacing: 'Betűköz', animations: 'Animációk', highContrast: 'Magas Kontraszt', colorBlind: 'Színvakság', reset: 'Visszaállítás', language: 'Nyelv', selectLanguage: 'Nyelv Kiválasztása' },
  colors: { green: 'Iszlám Zöld', gold: 'Arany', blue: 'Kék', purple: 'Lila', red: 'Piros', teal: 'Zöldeskék', orange: 'Narancssárga', pink: 'Rózsaszín', indigo: 'Indigó', brown: 'Barna' },
  fontSizes: { xsmall: 'Nagyon Kicsi', small: 'Kicsi', medium: 'Közepes', large: 'Nagy', xlarge: 'Nagyon Nagy', xxlarge: 'Hatalmas' },
  colorBlind: { none: 'Normál', protanopia: 'Protanópia', deuteranopia: 'Deuteranópia', tritanopia: 'Tritanópia' },
  common: { loading: 'Betöltés...', error: 'Hiba történt', retry: 'Újra', save: 'Mentés', cancel: 'Mégse', confirm: 'Megerősítés', back: 'Vissza', next: 'Következő', previous: 'Előző', search: 'Keresés', notFound: 'Nem Található', comingSoon: 'Hamarosan' },
  calendar: { year: 'Év', month: 'Hónap', sacredMonth: 'Szent Hónap', whiteDays: 'Fehér Napok', islamicEvent: 'Iszlám Esemény', currentDay: 'Aktuális Nap', upcomingEvents: 'Közelgő Események', sacredMonths: 'Szent Hónapok', tapFullCalendar: 'Érintse meg a teljes Hidzsri naptárhoz', gregorianDate: 'Gergely-naptár Dátum', hijriYear: 'H', muharram: 'Muharram', safar: 'Szafar', rabiAlAwwal: 'Rabi al-Avval', rabiAlThani: 'Rabi asz-Száni', jumadaAlUla: 'Dzsumáda al-Úla', jumadaAlThani: 'Dzsumáda asz-Szánija', rajab: 'Radzsab', shaban: 'Sabán', ramadan: 'Ramadán', shawwal: 'Savvál', dhuAlQidah: 'Dhul-Kida', dhuAlHijjah: 'Dhul-Hiddzsa', monthNum: 'Hónap' },
  quran: { title: 'Szent Korán', searchPlaceholder: 'Szúra vagy vers keresése...', bookmarks: 'Könyvjelzők', lastRead: 'Utoljára Olvasott', comingSoon: 'Hamarosan', contentComingSoon: 'A Korán tartalma itt kerül hozzáadásra', collections: 'Gyűjtemények', selectCollection: 'Válassz gyűjteményt', sections: 'Fejezetek', selectSection: 'Válassz fejezetet', hadithNumber: 'Hadith sorszám', arabicText: 'Arab szöveg', translation: 'Fordítás', loadingHadiths: 'Hadithok betöltése...', errorLoading: 'Hiba a betöltéskor', noHadiths: 'Nincs hadith ebben a fejezetben', totalHadiths: 'Összes hadith', allCollections: 'Minden gyűjtemény', backToCollections: 'Vissza a gyűjteményekhez', backToSections: 'Vissza a fejezetekhez' },
  hadith: { title: 'Hadísz', searchPlaceholder: 'Hadísz keresése...', sahihBukhari: 'Szahíh al-Bukhári', sahihMuslim: 'Szahíh Muszlim', comingSoon: 'Hamarosan', contentComingSoon: 'A Próféta ﷺ hadíszai itt kerülnek hozzáadásra' },
  sound: { title: 'Recitálások', selectReciter: 'Recitáló Kiválasztása', reciters: 'Recitálók', recitations: 'Korán Recitálások', murattal: 'Murattal', mujawwad: 'Mudzsavvad' },
  rulings: { title: 'Szabályok', searchPlaceholder: 'Szabály keresése...', prayerRulings: 'Ima Szabályok', fastingRulings: 'Böjt Szabályok', zakatRulings: 'Zakát Szabályok', hajjRulings: 'Hadzs Szabályok', breastfeedingRulings: 'Szoptatási Szabályok', purificationRulings: 'Tisztulási Szabályok', comingSoon: 'Hamarosan' },
  dhikr: { currentDhikr: 'Aktuális Dhikr', tapToCount: 'Érintse meg a Számoláshoz', resetCount: 'Számláló Visszaállítása', dhikrNotFound: 'Dhikr nem található', backToSelection: 'Vissza a Dhikr Kiválasztáshoz', tasbeehah: 'számolás', subhanallah: 'SzubhánAllah', alhamdulillah: 'Alhamdulillah', allahuakbar: 'Allahu Akbar', lailaha: 'Lá iláha illalláh', astaghfirullah: 'Asztaǧfirulláh', lahawla: 'Lá havla valá kuvvata illá billáh', subhanallahwabihamdi: 'SzubhánAlláhi va bihamdihi', salawat: 'Áldások a Prófétára ﷺ', descSubhanallah: 'Allah dicsőítése', descAlhamdulillah: 'Allah magasztalása', descAllahuakbar: 'Allah nagyítása', descLailaha: 'Hitvallás', descAstaghfirullah: 'Megbocsátás keresése', descLahawla: 'Bizalom kijelentése', descSubhanallahwabihamdi: 'Két könnyű szó a nyelven', descSalawat: 'Ó Allah, áldd meg Prófétánkat Muhammadot' },
  tasbeeh: { title: 'Taszbeeh Oldalak', morningAdhkar: 'Reggeli Adhkár', eveningAdhkar: 'Esti Adhkár', sleepAdhkar: 'Alvás Adhkár', variousAdhkar: 'Különböző Adhkár', adhkarCount: 'adhkár', resetAll: 'Összes Számláló Visszaállítása', done: 'Kész ✓', morningEveningAdhkar: 'Reggeli, esti és alvási adhkár', customizeSettings: 'Színek, betűtípusok és felület testreszabása' },
  preparations: { title: 'Előkészületek', quranLearning: 'Szent Korán', quranLearningDesc: 'Korán és Tadzsviid tanulása', breastfeedingRulings: 'Szoptatási Szabályok', breastfeedingDesc: 'Fiqh szabályok a szoptatásról', threeDContent: '3D Tartalom', threeDDesc: 'Interaktív oktatási tartalom', interactiveMap: 'Interaktív Térkép', interactiveMapDesc: 'Fedezd fel az iszlám világot', mapInfo: 'Az iszlám világ interaktív térképe információkkal minden országról hozzáadásra kerül', comingSoon: 'Hamarosan' },
  prayerDetail: { prayer: 'Ima', rakaat: 'Rákaát', fard: 'Kötelező', sunnahBefore: 'Szunnah Előtte', sunnahAfter: 'Szunnah Utána', completed: 'Befejezve', required: 'Szükséges', addRakaat: 'Ráka Hozzáadása', completedLabel: 'Befejezve', virtues: 'Erényei', resetCount: 'Számláló Visszaállítása', prayerNotFound: 'Ima nem található', backToHome: 'Vissza a Főoldalra' },
  islamicEvent: {
    practices: 'Ajánlott Gyakorlatok', duaOrDhikr: 'Dua vagy Dhikr', quranVerses: 'Korán Versek', surah: 'Szúra', verse: 'Vers', backToCalendar: 'Vissza a Naptárhoz', eventNotFound: 'Esemény nem található', month: 'Hónap', typeHoliday: 'Ünnep', typeFasting: 'Böjt', typeSpecial: 'Különleges', typeWorship: 'Istentisztelet',
    events: {
      newYear: { name: 'Iszlám Újév', description: 'Az új Hidzsri év kezdete', fullDescription: 'Muharram 1. jelzi az új iszlám év kezdetét, megemlékezve a Próféta ﷺ Hidzsrájáról Mekkából Medinába.', practices: ['Elmélkedni az elmúlt évről és megbánni', 'Kegyes szándékokat kitűzni az új évre', 'Imádkozni a jóságért és áldásokért'] },
      ashura: { name: 'Ásúrá Napja', description: 'Böjt Ásúrán (ajánlott a 9-én is böjtölni)', fullDescription: 'Ásúrá Muharram 10. napja, amikor Allah megmentette Múszát és népét a Fáraótól.', practices: ['Böjtölni Muharram 9-én és 10-én', 'Dhikr és dua növelése', 'Alamizsna adása'] },
      mawlid: { name: 'A Próféta Születésnapja', description: 'A Próféta ﷺ születésének megemlékezése', fullDescription: 'Rabi al-Avval 12. jelzi Muhammad Próféta ﷺ születését.', practices: ['Bőségesen áldásokat küldeni a Prófétára ﷺ', 'Olvasni a Próféta életrajzát', 'Tanulni a Próféta ﷺ jelleméből'] },
      israMiraj: { name: 'Iszrá és Mi\'rádzs', description: 'Áldott és kitüntetett éjszaka', fullDescription: 'Az Éjszakai Utazás és Mennybemenetel amikor a Próféta ﷺ a Szent Mecsetből az al-Aksza Mecsetbe vitetett.', practices: ['Bőségesen áldásokat küldeni a Prófétára ﷺ', 'Legalább két raka imádkozása', 'Szúra al-Iszrá olvasása', 'Allah csodáinak szemlélése'] },
      nisfShaban: { name: 'Sabán Közepének Éjszakája', description: 'A Kibla megváltoztatásának éjszakája', fullDescription: 'Sabán közepének éjszakája áldott éjszaka, amikor a Kibla Jeruzsálemről a Kaabára változott.', practices: ['Dua és isztighfár növelése', 'Kijám al-lajl imádkozása', 'A Kibla változás történetének szemlélése'] },
      ramadanStart: { name: 'Ramadán Kezdete', description: 'A böjt és a Korán hónapja', fullDescription: 'Az áldott Ramadán hónap a böjt, az ima és a Korán olvasásának hónapja.', practices: ['Az egész hónapot böjtölni', 'A Koránt olvasni és befejezni', 'Tarávih imádkozása', 'Jótékonyság növelése'] },
      lastTen: { name: 'Utolsó Tíz Éjszaka', description: 'Lajlat al-Qadr keresése páratlan éjszakákon', fullDescription: 'Ramadán utolsó tíz éjszakája tartalmazza Lajlat al-Qadrt, amely jobb ezer hónapnál.', practices: ['Kijám imádkozása páratlan éjszakákon (21, 23, 25, 27, 29)', 'I\'tikáf a mecsetben', 'Dua és dhikr növelése', 'Korán recitálása'] },
      eidFitr: { name: 'Íd al-Fitr', description: 'A böjtölő öröme és takbirát', fullDescription: 'Íd al-Fitr az öröm napja a Ramadán böjt után.', practices: ['Takbirát recitálása az Íd éjszakájától az Íd imáig', 'Íd ima elvégzése', 'Zakát al-Fitr megfizetése az ima előtt', 'Rokonok meglátogatása'] },
      arafah: { name: 'Arafat Napja', description: 'Legjobb nap nem zarándokok számára, böjt két évet engesztel', fullDescription: 'Arafat Napja Dhul Hiddzsa 9. napja, a legjobb nap amelyen a nap felkelt.', practices: ['Böjt Arafat Napján (nem zarándokoknak)', 'Dhikr és dua növelése', 'Megbánás és megbocsátás keresése'] },
      eidAdha: { name: 'Íd al-Adha', description: 'Az áldozat napja és Tasrik napok', fullDescription: 'Íd al-Adha az áldozat napja (Dhul Hiddzsa 10.) amelyet a Tasrik napok követnek.', practices: ['Takbirát recitálása a Tasrik napokon', 'Íd ima elvégzése', 'Az áldozat bemutatása', 'Családi kötelékek fenntartása'] },
    },
  },
};
