// Italian Translation
import type { TranslationKeys } from './ar';

export const it: TranslationKeys = {
  app: { name: 'Islami', tagline: 'Il Tuo Compagno Islamico' },
  nav: { home: 'Home', quran: 'Corano', hadith: 'Hadith', rulings: 'Norme', sound: 'Audio', counters: 'Contatori', settings: 'Impostazioni' },
  home: { prayerTimes: 'Orari di Preghiera', nextPrayer: 'Prossima Preghiera', hijriCalendar: 'Calendario Hijri', today: 'Oggi', fajr: 'Fajr', sunrise: 'Alba', dhuhr: 'Dhuhr', asr: 'Asr', maghrib: 'Maghrib', isha: 'Isha' },
  counters: { title: 'Contatori', dhikr: 'Dhikr', tasbeeh: 'Tasbeeh', preparations: 'Preparazioni', selectDhikr: 'Seleziona Dhikr', count: 'Contare', reset: 'Resetta', target: 'Obiettivo' },
  settings: { title: 'Impostazioni', theme: 'Tema', light: 'Chiaro', dark: 'Scuro', auto: 'Automatico', primaryColor: 'Colore Primario', fontSize: 'Dimensione Carattere', fontFamily: 'Tipo di Carattere', background: 'Stile Sfondo', navPosition: 'Posizione Navigazione', bottom: 'Basso', right: 'Destra', left: 'Sinistra', borderRadius: 'Raggio Bordo', spacing: 'Spaziatura', fontWeight: 'Peso Carattere', lineHeight: 'Altezza Linea', letterSpacing: 'Spaziatura Lettere', animations: 'Animazioni', highContrast: 'Alto Contrasto', colorBlind: 'Daltonismo', reset: 'Resetta', language: 'Lingua', selectLanguage: 'Seleziona Lingua' },
  colors: { green: 'Verde Islamico', gold: 'Oro', blue: 'Blu', purple: 'Viola', red: 'Rosso', teal: 'Verde Acqua', orange: 'Arancione', pink: 'Rosa', indigo: 'Indaco', brown: 'Marrone' },
  fontSizes: { xsmall: 'Molto Piccolo', small: 'Piccolo', medium: 'Medio', large: 'Grande', xlarge: 'Molto Grande', xxlarge: 'Enorme' },
  colorBlind: { none: 'Normale', protanopia: 'Protanopia', deuteranopia: 'Deuteranopia', tritanopia: 'Tritanopia' },
  common: { loading: 'Caricamento...', error: 'Si è verificato un errore', retry: 'Riprova', save: 'Salva', cancel: 'Annulla', confirm: 'Conferma', back: 'Indietro', next: 'Avanti', previous: 'Precedente', search: 'Cerca', notFound: 'Non Trovato', comingSoon: 'Prossimamente' },
  calendar: { year: 'Anno', month: 'Mese', sacredMonth: 'Mese Sacro', whiteDays: 'Giorni Bianchi', islamicEvent: 'Evento Islamico', currentDay: 'Giorno Corrente', upcomingEvents: 'Prossimi Eventi', sacredMonths: 'Mesi Sacri', tapFullCalendar: 'Tocca per il calendario Hijri completo', gregorianDate: 'Data Gregoriana', hijriYear: 'E.', muharram: 'Muharram', safar: 'Safar', rabiAlAwwal: 'Rabi al-Awwal', rabiAlThani: 'Rabi al-Thani', jumadaAlUla: 'Jumada al-Ula', jumadaAlThani: 'Jumada al-Thani', rajab: 'Rajab', shaban: 'Sha\'ban', ramadan: 'Ramadan', shawwal: 'Shawwal', dhuAlQidah: 'Dhul-Qi\'dah', dhuAlHijjah: 'Dhul-Hijjah', monthNum: 'Mese' },
  quran: { title: 'Sacro Corano', searchPlaceholder: 'Cerca una sura o un verso...', bookmarks: 'Segnalibri', lastRead: 'Ultima Lettura', comingSoon: 'Prossimamente', contentComingSoon: 'Il contenuto del Corano sarà aggiunto qui', collections: 'Collezioni', selectCollection: 'Seleziona raccolta', sections: 'Capitoli', selectSection: 'Seleziona capitolo', hadithNumber: 'Hadith n.', arabicText: 'Testo arabo', translation: 'Traduzione', loadingHadiths: 'Caricamento hadith...', errorLoading: 'Errore durante il caricamento', noHadiths: 'Nessun hadith in questo capitolo', totalHadiths: 'Totale hadith', allCollections: 'Tutte le collezioni', backToCollections: 'Torna alle collezioni', backToSections: 'Torna ai capitoli' },
  hadith: { title: 'Hadith', searchPlaceholder: 'Cerca un hadith...', sahihBukhari: 'Sahih al-Bukhari', sahihMuslim: 'Sahih Muslim', comingSoon: 'Prossimamente', contentComingSoon: 'Gli hadith del Profeta ﷺ saranno aggiunti qui' },
  sound: { title: 'Recitazioni', selectReciter: 'Seleziona Recitatore', reciters: 'Recitatori', recitations: 'Recitazioni del Corano', murattal: 'Murattal', mujawwad: 'Mujawwad' },
  rulings: { title: 'Norme', searchPlaceholder: 'Cerca una norma...', prayerRulings: 'Norme della Preghiera', fastingRulings: 'Norme del Digiuno', zakatRulings: 'Norme della Zakat', hajjRulings: 'Norme dell\'Hajj', breastfeedingRulings: 'Norme sull\'Allattamento', purificationRulings: 'Norme della Purificazione', comingSoon: 'Prossimamente' },
  dhikr: { currentDhikr: 'Dhikr Attuale', tapToCount: 'Tocca per Contare', resetCount: 'Resetta Contatore', dhikrNotFound: 'Dhikr non trovato', backToSelection: 'Torna alla Selezione Dhikr', tasbeehah: 'conteggio', subhanallah: 'SubhanAllah', alhamdulillah: 'Alhamdulillah', allahuakbar: 'Allahu Akbar', lailaha: 'La ilaha illallah', astaghfirullah: 'Astaghfirullah', lahawla: 'La hawla wala quwwata illa billah', subhanallahwabihamdi: 'SubhanAllahi wa bihamdihi', salawat: 'Benedizioni sul Profeta ﷺ', descSubhanallah: 'Glorificare Allah', descAlhamdulillah: 'Lodare Allah', descAllahuakbar: 'Magnificare Allah', descLailaha: 'Dichiarazione di Fede', descAstaghfirullah: 'Cercare il Perdono', descLahawla: 'Dichiarazione di Fiducia', descSubhanallahwabihamdi: 'Due parole leggere sulla lingua', descSalawat: 'O Allah, benedici il nostro Profeta Muhammad' },
  tasbeeh: { title: 'Pagine di Tasbeeh', morningAdhkar: 'Adhkar del Mattino', eveningAdhkar: 'Adhkar della Sera', sleepAdhkar: 'Adhkar del Sonno', variousAdhkar: 'Adhkar Vari', adhkarCount: 'adhkar', resetAll: 'Resetta Tutti i Contatori', done: 'Fatto ✓', morningEveningAdhkar: 'Adhkar del mattino, sera e sonno', customizeSettings: 'Personalizza colori, caratteri e interfaccia' },
  preparations: { title: 'Preparazioni', quranLearning: 'Sacro Corano', quranLearningDesc: 'Imparare Corano e Tajwid', breastfeedingRulings: 'Norme sull\'Allattamento', breastfeedingDesc: 'Norme di fiqh sull\'allattamento', threeDContent: 'Contenuto 3D', threeDDesc: 'Contenuto educativo interattivo', interactiveMap: 'Mappa Interattiva', interactiveMapDesc: 'Esplorare il mondo islamico', mapInfo: 'Sarà aggiunta una mappa interattiva del mondo islamico con informazioni su ogni paese', comingSoon: 'Prossimamente' },
  prayerDetail: { prayer: 'Preghiera', rakaat: 'Rakaat', fard: 'Obbligatorio', sunnahBefore: 'Sunnah Prima', sunnahAfter: 'Sunnah Dopo', completed: 'Completato', required: 'Richiesto', addRakaat: 'Aggiungi Raka', completedLabel: 'Completato', virtues: 'Virtù di', resetCount: 'Resetta Contatore', prayerNotFound: 'Preghiera non trovata', backToHome: 'Torna alla Home' },
  islamicEvent: {
    practices: 'Pratiche Raccomandate', duaOrDhikr: 'Dua o Dhikr', quranVerses: 'Versi del Corano', surah: 'Sura', verse: 'Verso', backToCalendar: 'Torna al Calendario', eventNotFound: 'Evento non trovato', month: 'Mese', typeHoliday: 'Festività', typeFasting: 'Digiuno', typeSpecial: 'Speciale', typeWorship: 'Adorazione',
    events: {
      newYear: { name: 'Capodanno Islamico', description: 'Inizio del nuovo anno Hijri', fullDescription: 'Il 1° Muharram segna l\'inizio del nuovo anno islamico, commemorando l\'Egira del Profeta ﷺ dalla Mecca a Medina.', practices: ['Riflettere sull\'anno passato e pentirsi', 'Stabilire buoni propositi per il nuovo anno', 'Pregare per il bene e le benedizioni'] },
      ashura: { name: 'Giorno di Ashura', description: 'Digiuno di Ashura (consigliato digiunare anche il 9)', fullDescription: 'Ashura è il 10 di Muharram, il giorno in cui Allah salvò Musa e il suo popolo dal Faraone. Il digiuno di questo giorno espia i peccati dell\'anno precedente.', practices: ['Digiunare il 9 e 10 di Muharram', 'Aumentare il dhikr e la dua', 'Fare elemosina'] },
      mawlid: { name: 'Nascita del Profeta', description: 'Commemorazione della nascita del Profeta ﷺ', fullDescription: 'Il 12 di Rabi al-Awwal segna la nascita del Profeta Muhammad ﷺ, un\'occasione per ricordare la sua nobile vita e il suo carattere.', practices: ['Inviare abbondanti benedizioni sul Profeta ﷺ', 'Leggere la biografia del Profeta', 'Imparare dal carattere del Profeta ﷺ'] },
      israMiraj: { name: 'Isra e Mi\'raj', description: 'Una notte benedetta e distinta', fullDescription: 'Il Viaggio Notturno e l\'Ascensione è quando il Profeta ﷺ fu portato dalla Moschea Sacra alla Moschea di al-Aqsa, poi ascese ai cieli.', practices: ['Inviare abbondanti benedizioni sul Profeta ﷺ', 'Pregare almeno due rakat', 'Leggere la Sura al-Isra', 'Riflettere sui miracoli di Allah'] },
      nisfShaban: { name: 'Notte di metà Sha\'ban', description: 'Notte del cambio di Qibla, ha un significato speciale', fullDescription: 'La notte di metà Sha\'ban è una notte benedetta in cui la Qibla fu cambiata da Gerusalemme alla Kaaba.', practices: ['Aumentare la dua e l\'istighfar', 'Pregare qiyam al-layl', 'Riflettere sulla storia del cambio di Qibla'] },
      ramadanStart: { name: 'Inizio del Ramadan', description: 'Mese del digiuno e del Corano', fullDescription: 'Il mese benedetto del Ramadan è il mese del digiuno, della preghiera e della recitazione del Corano.', practices: ['Digiunare l\'intero mese', 'Leggere e completare il Corano', 'Pregare Tarawih', 'Aumentare la carità'] },
      lastTen: { name: 'Ultime Dieci Notti', description: 'Cercare Laylat al-Qadr nelle notti dispari', fullDescription: 'Le ultime dieci notti del Ramadan contengono Laylat al-Qadr, che è migliore di mille mesi.', practices: ['Pregare qiyam nelle notti dispari (21, 23, 25, 27, 29)', 'Fare i\'tikaf nella moschea', 'Aumentare la dua e il dhikr', 'Recitare il Corano'] },
      eidFitr: { name: 'Eid al-Fitr', description: 'Gioia del digiunante e takbirat', fullDescription: 'Eid al-Fitr è il giorno di gioia dopo il digiuno del mese di Ramadan.', practices: ['Recitare i takbirat dalla notte dell\'Eid alla preghiera', 'Eseguire la preghiera dell\'Eid', 'Pagare la Zakat al-Fitr prima della preghiera', 'Visitare i parenti'] },
      arafah: { name: 'Giorno di Arafat', description: 'Miglior giorno per i non pellegrini, il digiuno espia due anni', fullDescription: 'Il Giorno di Arafat è il 9 di Dhul Hijjah, il miglior giorno in cui il sole sia sorto.', practices: ['Digiunare il Giorno di Arafat (per non pellegrini)', 'Aumentare il dhikr e la dua', 'Pentirsi e cercare il perdono'] },
      eidAdha: { name: 'Eid al-Adha', description: 'Giorno del sacrificio e giorni di Tashriq', fullDescription: 'Eid al-Adha è il giorno del sacrificio (10 Dhul Hijjah) seguito dai giorni di Tashriq.', practices: ['Recitare i takbirat durante i giorni di Tashriq', 'Eseguire la preghiera dell\'Eid', 'Offrire il sacrificio', 'Mantenere i legami familiari'] },
    },
  },
};
