// Dutch Translation
import type { TranslationKeys } from './ar';

export const nl: TranslationKeys = {
  app: { name: 'Islami', tagline: 'Jouw Islamitische Metgezel' },
  nav: { home: 'Home', quran: 'Koran', hadith: 'Hadith', rulings: 'Regels', sound: 'Audio', counters: 'Tellers', settings: 'Instellingen' },
  home: { prayerTimes: 'Gebedstijden', nextPrayer: 'Volgend Gebed', hijriCalendar: 'Hijri-kalender', today: 'Vandaag', fajr: 'Fajr', sunrise: 'Zonsopgang', dhuhr: 'Dhuhr', asr: 'Asr', maghrib: 'Maghrib', isha: 'Isha' },
  counters: { title: 'Tellers', dhikr: 'Dhikr', tasbeeh: 'Tasbeeh', preparations: 'Voorbereidingen', selectDhikr: 'Selecteer Dhikr', count: 'Tellen', reset: 'Resetten', target: 'Doel' },
  settings: { title: 'Instellingen', theme: 'Thema', light: 'Licht', dark: 'Donker', auto: 'Automatisch', primaryColor: 'Primaire Kleur', fontSize: 'Lettergrootte', fontFamily: 'Lettertype', background: 'Achtergrondstijl', navPosition: 'Navigatiepositie', bottom: 'Onder', right: 'Rechts', left: 'Links', borderRadius: 'Hoekradius', spacing: 'Ruimte', fontWeight: 'Lettergewicht', lineHeight: 'Regelhoogte', letterSpacing: 'Letterafstand', animations: 'Animaties', highContrast: 'Hoog Contrast', colorBlind: 'Kleurenblind', reset: 'Resetten', language: 'Taal', selectLanguage: 'Selecteer Taal' },
  colors: { green: 'Islamitisch Groen', gold: 'Goud', blue: 'Blauw', purple: 'Paars', red: 'Rood', teal: 'Blauwgroen', orange: 'Oranje', pink: 'Roze', indigo: 'Indigo', brown: 'Bruin' },
  fontSizes: { xsmall: 'Extra Klein', small: 'Klein', medium: 'Middel', large: 'Groot', xlarge: 'Extra Groot', xxlarge: 'Enorm' },
  colorBlind: { none: 'Normaal', protanopia: 'Protanopie', deuteranopia: 'Deuteranopie', tritanopia: 'Tritanopie' },
  common: { loading: 'Laden...', error: 'Er is een fout opgetreden', retry: 'Opnieuw', save: 'Opslaan', cancel: 'Annuleren', confirm: 'Bevestigen', back: 'Terug', next: 'Volgende', previous: 'Vorige', search: 'Zoeken', notFound: 'Niet Gevonden', comingSoon: 'Binnenkort' },
  calendar: { year: 'Jaar', month: 'Maand', sacredMonth: 'Heilige Maand', whiteDays: 'Witte Dagen', islamicEvent: 'Islamitisch Evenement', currentDay: 'Huidige Dag', upcomingEvents: 'Komende Evenementen', sacredMonths: 'Heilige Maanden', tapFullCalendar: 'Tik voor de volledige Hijri-kalender', gregorianDate: 'Gregoriaanse Datum', hijriYear: 'H', muharram: 'Muharram', safar: 'Safar', rabiAlAwwal: 'Rabi al-Awwal', rabiAlThani: 'Rabi al-Thani', jumadaAlUla: 'Jumada al-Ula', jumadaAlThani: 'Jumada al-Thani', rajab: 'Rajab', shaban: 'Sha\'ban', ramadan: 'Ramadan', shawwal: 'Shawwal', dhuAlQidah: 'Dhul-Qi\'dah', dhuAlHijjah: 'Dhul-Hijjah', monthNum: 'Maand' },
  quran: { title: 'Heilige Koran', searchPlaceholder: 'Zoek een soera of vers...', bookmarks: 'Bladwijzers', lastRead: 'Laatst Gelezen', comingSoon: 'Binnenkort', contentComingSoon: 'Koraninhoud wordt hier toegevoegd', collections: 'Collecties', selectCollection: 'Selecteer collectie', sections: 'Hoofdstukken', selectSection: 'Selecteer hoofdstuk', hadithNumber: 'Hadith nr.', arabicText: 'Arabische tekst', translation: 'Vertaling', loadingHadiths: 'Hadiths laden...', errorLoading: 'Fout bij laden', noHadiths: 'Geen hadiths in dit hoofdstuk', totalHadiths: 'Totaal hadiths', allCollections: 'Alle collecties', backToCollections: 'Terug naar collecties', backToSections: 'Terug naar hoofdstukken' },
  hadith: { title: 'Hadith', searchPlaceholder: 'Zoek een hadith...', sahihBukhari: 'Sahih al-Bukhari', sahihMuslim: 'Sahih Muslim', comingSoon: 'Binnenkort', contentComingSoon: 'Hadiths van de Profeet ﷺ worden hier toegevoegd' },
  sound: { title: 'Recitaties', selectReciter: 'Selecteer Recitator', reciters: 'Recitatoren', recitations: 'Koranrecitaties', murattal: 'Murattal', mujawwad: 'Mujawwad' },
  rulings: { title: 'Regels', searchPlaceholder: 'Zoek een regel...', prayerRulings: 'Gebedsregels', fastingRulings: 'Vastenregels', zakatRulings: 'Zakatregels', hajjRulings: 'Hajjregels', breastfeedingRulings: 'Borstvoedingsregels', purificationRulings: 'Reinigingsregels', comingSoon: 'Binnenkort' },
  dhikr: { currentDhikr: 'Huidige Dhikr', tapToCount: 'Tik om te Tellen', resetCount: 'Teller Resetten', dhikrNotFound: 'Dhikr niet gevonden', backToSelection: 'Terug naar Dhikr Selectie', tasbeehah: 'telling', subhanallah: 'SubhanAllah', alhamdulillah: 'Alhamdulillah', allahuakbar: 'Allahu Akbar', lailaha: 'La ilaha illallah', astaghfirullah: 'Astaghfirullah', lahawla: 'La hawla wala quwwata illa billah', subhanallahwabihamdi: 'SubhanAllahi wa bihamdihi', salawat: 'Zegeningen over de Profeet ﷺ', descSubhanallah: 'Allah verheerlijken', descAlhamdulillah: 'Allah prijzen', descAllahuakbar: 'Allah vergroten', descLailaha: 'Geloofsbelijdenis', descAstaghfirullah: 'Vergeving zoeken', descLahawla: 'Verklaring van Vertrouwen', descSubhanallahwabihamdi: 'Twee lichte woorden op de tong', descSalawat: 'O Allah, zegen onze Profeet Muhammad' },
  tasbeeh: { title: 'Tasbeeh Pagina\'s', morningAdhkar: 'Ochtend Adhkar', eveningAdhkar: 'Avond Adhkar', sleepAdhkar: 'Slaap Adhkar', variousAdhkar: 'Diverse Adhkar', adhkarCount: 'adhkar', resetAll: 'Alle Tellers Resetten', done: 'Klaar ✓', morningEveningAdhkar: 'Ochtend-, avond- en slaap-adhkar', customizeSettings: 'Kleuren, lettertypen en interface aanpassen' },
  preparations: { title: 'Voorbereidingen', quranLearning: 'Heilige Koran', quranLearningDesc: 'Koran en Tajwid leren', breastfeedingRulings: 'Borstvoedingsregels', breastfeedingDesc: 'Fiqh-regels over borstvoeding', threeDContent: '3D Inhoud', threeDDesc: 'Interactieve educatieve inhoud', interactiveMap: 'Interactieve Kaart', interactiveMapDesc: 'De islamitische wereld verkennen', mapInfo: 'Een interactieve kaart van de islamitische wereld met informatie over elk land wordt toegevoegd', comingSoon: 'Binnenkort' },
  prayerDetail: { prayer: 'Gebed', rakaat: 'Rakaat', fard: 'Verplicht', sunnahBefore: 'Sunnah Ervoor', sunnahAfter: 'Sunnah Erna', completed: 'Voltooid', required: 'Vereist', addRakaat: 'Raka Toevoegen', completedLabel: 'Voltooid', virtues: 'Deugden van', resetCount: 'Teller Resetten', prayerNotFound: 'Gebed niet gevonden', backToHome: 'Terug naar Home' },
  islamicEvent: {
    practices: 'Aanbevolen Praktijken', duaOrDhikr: 'Dua of Dhikr', quranVerses: 'Koranverzen', surah: 'Soera', verse: 'Vers', backToCalendar: 'Terug naar Kalender', eventNotFound: 'Evenement niet gevonden', month: 'Maand', typeHoliday: 'Feestdag', typeFasting: 'Vasten', typeSpecial: 'Speciaal', typeWorship: 'Aanbidding',
    events: {
      newYear: { name: 'Islamitisch Nieuwjaar', description: 'Begin van het nieuwe Hijri-jaar', fullDescription: 'De 1e Muharram markeert het begin van het nieuwe islamitische jaar, ter herdenking van de Hijra van de Profeet ﷺ van Mekka naar Medina.', practices: ['Reflecteren op het afgelopen jaar en berouw tonen', 'Goede voornemens maken voor het nieuwe jaar', 'Bidden voor goedheid en zegeningen'] },
      ashura: { name: 'Dag van Ashura', description: 'Vasten op Ashura (aanbevolen ook op de 9e te vasten)', fullDescription: 'Ashura is de 10e Muharram, de dag waarop Allah Musa en zijn volk redde van de Farao.', practices: ['Vasten op de 9e en 10e Muharram', 'Dhikr en dua vermeerderen', 'Liefdadigheid geven'] },
      mawlid: { name: 'Geboorte van de Profeet', description: 'Herdenking van de geboorte van de Profeet ﷺ', fullDescription: 'De 12e Rabi al-Awwal markeert de geboorte van Profeet Muhammad ﷺ.', practices: ['Overvloedig zegeningen over de Profeet ﷺ sturen', 'De biografie van de Profeet lezen', 'Leren van het karakter van de Profeet ﷺ'] },
      israMiraj: { name: 'Isra en Mi\'raj', description: 'Een gezegende en bijzondere nacht', fullDescription: 'De Nachtreis en Hemelvaart is toen de Profeet ﷺ van de Heilige Moskee naar de al-Aqsa Moskee werd gebracht.', practices: ['Overvloedig zegeningen over de Profeet ﷺ sturen', 'Minstens twee rakat bidden', 'Soera al-Isra lezen', 'Nadenken over Allahs wonderen'] },
      nisfShaban: { name: 'Nacht van midden Sha\'ban', description: 'Nacht van de Qibla-verandering', fullDescription: 'De nacht van midden Sha\'ban is een gezegende nacht toen de Qibla werd veranderd van Jeruzalem naar de Kaaba.', practices: ['Dua en istighfar vermeerderen', 'Qiyam al-layl bidden', 'Nadenken over het verhaal van de Qibla-verandering'] },
      ramadanStart: { name: 'Begin van Ramadan', description: 'Maand van vasten en Koran', fullDescription: 'De gezegende maand Ramadan is de maand van vasten, gebed en Koranrecitatie.', practices: ['De hele maand vasten', 'De Koran lezen en voltooien', 'Tarawih bidden', 'Liefdadigheid vermeerderen'] },
      lastTen: { name: 'Laatste Tien Nachten', description: 'Laylat al-Qadr zoeken in oneven nachten', fullDescription: 'De laatste tien nachten van Ramadan bevatten Laylat al-Qadr, die beter is dan duizend maanden.', practices: ['Qiyam bidden in oneven nachten (21, 23, 25, 27, 29)', 'I\'tikaf in de moskee', 'Dua en dhikr vermeerderen', 'De Koran reciteren'] },
      eidFitr: { name: 'Eid al-Fitr', description: 'Vreugde van de vastende en takbirat', fullDescription: 'Eid al-Fitr is de dag van vreugde na het vasten van de maand Ramadan.', practices: ['Takbirat reciteren vanaf de nacht van Eid tot het Eid-gebed', 'Het Eid-gebed verrichten', 'Zakat al-Fitr betalen vóór het gebed', 'Familie bezoeken'] },
      arafah: { name: 'Dag van Arafat', description: 'Beste dag voor niet-pelgrims, vasten verzoent twee jaar', fullDescription: 'De Dag van Arafat is de 9e Dhul Hijjah, de beste dag waarop de zon is opgegaan.', practices: ['Vasten op de Dag van Arafat (voor niet-pelgrims)', 'Dhikr en dua vermeerderen', 'Berouw tonen en vergeving zoeken'] },
      eidAdha: { name: 'Eid al-Adha', description: 'Dag van het offer en dagen van Tashriq', fullDescription: 'Eid al-Adha is de dag van het offer (10e Dhul Hijjah) gevolgd door de dagen van Tashriq.', practices: ['Takbirat reciteren tijdens de dagen van Tashriq', 'Het Eid-gebed verrichten', 'Het offer brengen', 'Familiebanden onderhouden'] },
    },
  },
};
