// Norwegian Translation
import type { TranslationKeys } from './ar';

export const no: TranslationKeys = {
  app: { name: 'Islami', tagline: 'Din Islamske Følgesvenn' },
  nav: { home: 'Hjem', quran: 'Koranen', hadith: 'Hadith', rulings: 'Regler', sound: 'Lyd', counters: 'Tellere', settings: 'Innstillinger' },
  home: { prayerTimes: 'Bønnetider', nextPrayer: 'Neste Bønn', hijriCalendar: 'Hijrikalender', today: 'I dag', fajr: 'Fajr', sunrise: 'Soloppgang', dhuhr: 'Dhuhr', asr: 'Asr', maghrib: 'Maghrib', isha: 'Isha' },
  counters: { title: 'Tellere', dhikr: 'Dhikr', tasbeeh: 'Tasbeeh', preparations: 'Forberedelser', selectDhikr: 'Velg Dhikr', count: 'Telle', reset: 'Tilbakestill', target: 'Mål' },
  settings: { title: 'Innstillinger', theme: 'Tema', light: 'Lyst', dark: 'Mørkt', auto: 'Automatisk', primaryColor: 'Primærfarge', fontSize: 'Skriftstørrelse', fontFamily: 'Skrifttype', background: 'Bakgrunnsstil', navPosition: 'Navigasjonsposisjon', bottom: 'Bunn', right: 'Høyre', left: 'Venstre', borderRadius: 'Hjørneradius', spacing: 'Avstand', fontWeight: 'Skrifttykkelse', lineHeight: 'Linjehøyde', letterSpacing: 'Bokstavavstand', animations: 'Animasjoner', highContrast: 'Høy Kontrast', colorBlind: 'Fargeblindhet', reset: 'Tilbakestill', language: 'Språk', selectLanguage: 'Velg Språk' },
  colors: { green: 'Islamsk Grønn', gold: 'Gull', blue: 'Blå', purple: 'Lilla', red: 'Rød', teal: 'Blågrønn', orange: 'Oransje', pink: 'Rosa', indigo: 'Indigo', brown: 'Brun' },
  fontSizes: { xsmall: 'Ekstra Liten', small: 'Liten', medium: 'Medium', large: 'Stor', xlarge: 'Ekstra Stor', xxlarge: 'Enorm' },
  colorBlind: { none: 'Normal', protanopia: 'Protanopi', deuteranopia: 'Deuteranopi', tritanopia: 'Tritanopi' },
  common: { loading: 'Laster...', error: 'En feil oppstod', retry: 'Prøv igjen', save: 'Lagre', cancel: 'Avbryt', confirm: 'Bekreft', back: 'Tilbake', next: 'Neste', previous: 'Forrige', search: 'Søk', notFound: 'Ikke Funnet', comingSoon: 'Kommer Snart' },
  calendar: { year: 'År', month: 'Måned', sacredMonth: 'Hellig Måned', whiteDays: 'Hvite Dager', islamicEvent: 'Islamsk Hendelse', currentDay: 'Gjeldende Dag', upcomingEvents: 'Kommende Hendelser', sacredMonths: 'Hellige Måneder', tapFullCalendar: 'Trykk for fullstendig Hijrikalender', gregorianDate: 'Gregoriansk Dato', hijriYear: 'H', muharram: 'Muharram', safar: 'Safar', rabiAlAwwal: 'Rabi al-Awwal', rabiAlThani: 'Rabi al-Thani', jumadaAlUla: 'Jumada al-Ula', jumadaAlThani: 'Jumada al-Thani', rajab: 'Rajab', shaban: 'Sha\'ban', ramadan: 'Ramadan', shawwal: 'Shawwal', dhuAlQidah: 'Dhul-Qi\'dah', dhuAlHijjah: 'Dhul-Hijjah', monthNum: 'Måned' },
  quran: { title: 'Hellige Koranen', searchPlaceholder: 'Søk etter en sura eller vers...', bookmarks: 'Bokmerker', lastRead: 'Sist Lest', comingSoon: 'Kommer Snart', contentComingSoon: 'Koraninnhold legges til her', collections: 'Samlinger', selectCollection: 'Velg samling', sections: 'Kapitler', selectSection: 'Velg kapittel', hadithNumber: 'Hadith nr.', arabicText: 'Arabisk tekst', translation: 'Oversettelse', loadingHadiths: 'Laster hadither...', errorLoading: 'Feil ved lasting', noHadiths: 'Ingen hadither i dette kapittelet', totalHadiths: 'Totalt hadither', allCollections: 'Alle samlinger', backToCollections: 'Tilbake til samlinger', backToSections: 'Tilbake til kapitler' },
  hadith: { title: 'Hadith', searchPlaceholder: 'Søk etter en hadith...', sahihBukhari: 'Sahih al-Bukhari', sahihMuslim: 'Sahih Muslim', comingSoon: 'Kommer Snart', contentComingSoon: 'Profetens ﷺ hadither legges til her' },
  sound: { title: 'Resitasjoner', selectReciter: 'Velg Resitator', reciters: 'Resitatorer', recitations: 'Koranresitasjoner', murattal: 'Murattal', mujawwad: 'Mujawwad' },
  rulings: { title: 'Regler', searchPlaceholder: 'Søk etter en regel...', prayerRulings: 'Bønneregler', fastingRulings: 'Fasteregler', zakatRulings: 'Zakatregler', hajjRulings: 'Hajjregler', breastfeedingRulings: 'Ammeregler', purificationRulings: 'Renselsesregler', comingSoon: 'Kommer Snart' },
  dhikr: { currentDhikr: 'Gjeldende Dhikr', tapToCount: 'Trykk for å Telle', resetCount: 'Tilbakestill Teller', dhikrNotFound: 'Dhikr ikke funnet', backToSelection: 'Tilbake til Dhikr-valg', tasbeehah: 'telling', subhanallah: 'SubhanAllah', alhamdulillah: 'Alhamdulillah', allahuakbar: 'Allahu Akbar', lailaha: 'La ilaha illallah', astaghfirullah: 'Astaghfirullah', lahawla: 'La hawla wala quwwata illa billah', subhanallahwabihamdi: 'SubhanAllahi wa bihamdihi', salawat: 'Velsignelser over Profeten ﷺ', descSubhanallah: 'Forherlige Allah', descAlhamdulillah: 'Prise Allah', descAllahuakbar: 'Forstørre Allah', descLailaha: 'Trosbekjennelse', descAstaghfirullah: 'Søke Tilgivelse', descLahawla: 'Erklæring om Tillit', descSubhanallahwabihamdi: 'To lette ord på tungen', descSalawat: 'O Allah, velsign vår Profet Muhammad' },
  tasbeeh: { title: 'Tasbeeh-sider', morningAdhkar: 'Morgen-Adhkar', eveningAdhkar: 'Kveld-Adhkar', sleepAdhkar: 'Søvn-Adhkar', variousAdhkar: 'Diverse Adhkar', adhkarCount: 'adhkar', resetAll: 'Tilbakestill Alle Tellere', done: 'Ferdig ✓', morningEveningAdhkar: 'Morgen-, kveld- og søvn-adhkar', customizeSettings: 'Tilpass farger, skrifttyper og grensesnitt' },
  preparations: { title: 'Forberedelser', quranLearning: 'Hellige Koranen', quranLearningDesc: 'Lære Koranen og Tajwid', breastfeedingRulings: 'Ammeregler', breastfeedingDesc: 'Fiqh-regler om amming', threeDContent: '3D-innhold', threeDDesc: 'Interaktivt utdanningsinnhold', interactiveMap: 'Interaktivt Kart', interactiveMapDesc: 'Utforsk den islamske verden', mapInfo: 'Et interaktivt kart over den islamske verden med informasjon om hvert land legges til', comingSoon: 'Kommer Snart' },
  prayerDetail: { prayer: 'Bønn', rakaat: 'Rakaat', fard: 'Obligatorisk', sunnahBefore: 'Sunnah Før', sunnahAfter: 'Sunnah Etter', completed: 'Fullført', required: 'Påkrevd', addRakaat: 'Legg til Raka', completedLabel: 'Fullført', virtues: 'Dyder av', resetCount: 'Tilbakestill Teller', prayerNotFound: 'Bønn ikke funnet', backToHome: 'Tilbake til Hjem' },
  islamicEvent: {
    practices: 'Anbefalte Praksiser', duaOrDhikr: 'Dua eller Dhikr', quranVerses: 'Koranvers', surah: 'Sura', verse: 'Vers', backToCalendar: 'Tilbake til Kalenderen', eventNotFound: 'Hendelse ikke funnet', month: 'Måned', typeHoliday: 'Høytid', typeFasting: 'Faste', typeSpecial: 'Spesiell', typeWorship: 'Tilbedelse',
    events: {
      newYear: { name: 'Islamsk Nyttår', description: 'Begynnelsen av det nye Hijriåret', fullDescription: 'Den 1. Muharram markerer begynnelsen av det nye islamske året, til minne om Profetens ﷺ Hijra fra Mekka til Medina.', practices: ['Reflektere over det forgangne året og angre', 'Sette fromme intensjoner for det nye året', 'Be om godhet og velsignelser'] },
      ashura: { name: 'Ashura-dagen', description: 'Faste på Ashura (anbefalt å faste den 9. også)', fullDescription: 'Ashura er den 10. Muharram, dagen da Allah reddet Musa og hans folk fra Farao.', practices: ['Faste den 9. og 10. Muharram', 'Øke dhikr og dua', 'Gi almisser'] },
      mawlid: { name: 'Profetens Fødselsdag', description: 'Høytideliggjøring av Profetens ﷺ fødsel', fullDescription: 'Den 12. Rabi al-Awwal markerer Profeten Muhammads ﷺ fødsel.', practices: ['Sende rikelige velsignelser over Profeten ﷺ', 'Lese Profetens biografi', 'Lære av Profetens ﷺ karakter'] },
      israMiraj: { name: 'Isra og Mi\'raj', description: 'En velsignet og utmerket natt', fullDescription: 'Nattreisen og Himmelfarten er da Profeten ﷺ ble ført fra den Hellige Moskeen til al-Aqsa Moskeen.', practices: ['Sende rikelige velsignelser over Profeten ﷺ', 'Be minst to rakat', 'Lese Sura al-Isra', 'Reflektere over Allahs undere'] },
      nisfShaban: { name: 'Midt i Sha\'ban-natten', description: 'Natten for Qibla-endringen', fullDescription: 'Natten midt i Sha\'ban er en velsignet natt da Qibla ble endret fra Jerusalem til Kaaba.', practices: ['Øke dua og istighfar', 'Be qiyam al-layl', 'Reflektere over Qibla-endringens historie'] },
      ramadanStart: { name: 'Ramadans Begynnelse', description: 'Fastens og Koranens måned', fullDescription: 'Den velsignede Ramadan-måneden er fastens, bønnens og Koranresitasjonens måned.', practices: ['Faste hele måneden', 'Lese og fullføre Koranen', 'Be Tarawih', 'Øke veldedighet'] },
      lastTen: { name: 'Siste Ti Netter', description: 'Søke Laylat al-Qadr i odde netter', fullDescription: 'De siste ti nettene av Ramadan inneholder Laylat al-Qadr, som er bedre enn tusen måneder.', practices: ['Be qiyam i odde netter (21, 23, 25, 27, 29)', 'Utføre i\'tikaf i moskeen', 'Øke dua og dhikr', 'Resitere Koranen'] },
      eidFitr: { name: 'Eid al-Fitr', description: 'Den fastendes glede og takbirat', fullDescription: 'Eid al-Fitr er gledens dag etter Ramadans faste.', practices: ['Resitere takbirat fra Eid-natten til Eid-bønnen', 'Utføre Eid-bønnen', 'Betale Zakat al-Fitr før bønnen', 'Besøke slektninger'] },
      arafah: { name: 'Arafat-dagen', description: 'Beste dag for ikke-pilegrimer, faste soner to år', fullDescription: 'Arafat-dagen er den 9. Dhul Hijjah, den beste dagen solen har stått opp på.', practices: ['Faste på Arafat-dagen (for ikke-pilegrimer)', 'Øke dhikr og dua', 'Angre og søke tilgivelse'] },
      eidAdha: { name: 'Eid al-Adha', description: 'Offerdagen og Tashriq-dagene', fullDescription: 'Eid al-Adha er offerdagen (10. Dhul Hijjah) fulgt av Tashriq-dagene.', practices: ['Resitere takbirat under Tashriq-dagene', 'Utføre Eid-bønnen', 'Ofre dyret', 'Opprettholde familiebånd'] },
    },
  },
};
