// Polish Translation
import type { TranslationKeys } from './ar';

export const pl: TranslationKeys = {
  app: { name: 'Islami', tagline: 'Twój Islamski Towarzysz' },
  nav: { home: 'Strona główna', quran: 'Koran', hadith: 'Hadis', rulings: 'Orzeczenia', sound: 'Audio', counters: 'Liczniki', settings: 'Ustawienia' },
  home: { prayerTimes: 'Czasy Modlitw', nextPrayer: 'Następna Modlitwa', hijriCalendar: 'Kalendarz Hidżri', today: 'Dzisiaj', fajr: 'Fadżr', sunrise: 'Wschód Słońca', dhuhr: 'Zuhr', asr: 'Asr', maghrib: 'Maghrib', isha: 'Isza' },
  counters: { title: 'Liczniki', dhikr: 'Dhikr', tasbeeh: 'Tasbih', preparations: 'Przygotowania', selectDhikr: 'Wybierz Dhikr', count: 'Liczenie', reset: 'Resetuj', target: 'Cel' },
  settings: { title: 'Ustawienia', theme: 'Motyw', light: 'Jasny', dark: 'Ciemny', auto: 'Automatyczny', primaryColor: 'Kolor Główny', fontSize: 'Rozmiar Czcionki', fontFamily: 'Rodzina Czcionki', background: 'Styl Tła', navPosition: 'Pozycja Nawigacji', bottom: 'Dół', right: 'Prawo', left: 'Lewo', borderRadius: 'Promień Obramowania', spacing: 'Odstępy', fontWeight: 'Grubość Czcionki', lineHeight: 'Wysokość Linii', letterSpacing: 'Odstępy Liter', animations: 'Animacje', highContrast: 'Wysoki Kontrast', colorBlind: 'Ślepota Barw', reset: 'Resetuj', language: 'Język', selectLanguage: 'Wybierz Język' },
  colors: { green: 'Islamska Zieleń', gold: 'Złoto', blue: 'Niebieski', purple: 'Fioletowy', red: 'Czerwony', teal: 'Morski', orange: 'Pomarańczowy', pink: 'Różowy', indigo: 'Indygo', brown: 'Brązowy' },
  fontSizes: { xsmall: 'Bardzo Mały', small: 'Mały', medium: 'Średni', large: 'Duży', xlarge: 'Bardzo Duży', xxlarge: 'Ogromny' },
  colorBlind: { none: 'Normalny', protanopia: 'Protanopia', deuteranopia: 'Deuteranopia', tritanopia: 'Tritanopia' },
  common: { loading: 'Ładowanie...', error: 'Wystąpił błąd', retry: 'Ponów', save: 'Zapisz', cancel: 'Anuluj', confirm: 'Potwierdź', back: 'Wstecz', next: 'Dalej', previous: 'Poprzedni', search: 'Szukaj', notFound: 'Nie Znaleziono', comingSoon: 'Wkrótce' },
  calendar: { year: 'Rok', month: 'Miesiąc', sacredMonth: 'Święty Miesiąc', whiteDays: 'Białe Dni', islamicEvent: 'Wydarzenie Islamskie', currentDay: 'Bieżący Dzień', upcomingEvents: 'Nadchodzące Wydarzenia', sacredMonths: 'Święte Miesiące', tapFullCalendar: 'Dotknij, aby zobaczyć pełny kalendarz Hidżri', gregorianDate: 'Data Gregoriańska', hijriYear: 'H', muharram: 'Muharram', safar: 'Safar', rabiAlAwwal: 'Rabi al-Awwal', rabiAlThani: 'Rabi al-Thani', jumadaAlUla: 'Dżumada al-Ula', jumadaAlThani: 'Dżumada al-Thani', rajab: 'Radżab', shaban: 'Szaban', ramadan: 'Ramadan', shawwal: 'Szawwal', dhuAlQidah: 'Dhul-Kida', dhuAlHijjah: 'Dhul-Hidżdża', monthNum: 'Miesiąc' },
  quran: { title: 'Święty Koran', searchPlaceholder: 'Szukaj sury lub wersetu...', bookmarks: 'Zakładki', lastRead: 'Ostatnio Czytane', comingSoon: 'Wkrótce', contentComingSoon: 'Treść Koranu zostanie tutaj dodana' },
  hadith: { title: 'Hadis', searchPlaceholder: 'Szukaj hadisu...', sahihBukhari: 'Sahih al-Buchari', sahihMuslim: 'Sahih Muslim', comingSoon: 'Wkrótce', contentComingSoon: 'Hadisy Proroka ﷺ zostaną tutaj dodane' },
  sound: { title: 'Recytacje', selectReciter: 'Wybierz Recytatora', reciters: 'Recytatorzy', recitations: 'Recytacje Koranu', murattal: 'Murattal', mujawwad: 'Mudżawwad' },
  rulings: { title: 'Orzeczenia', searchPlaceholder: 'Szukaj orzeczenia...', prayerRulings: 'Orzeczenia Modlitwy', fastingRulings: 'Orzeczenia Postu', zakatRulings: 'Orzeczenia Zakatu', hajjRulings: 'Orzeczenia Hadżdżu', breastfeedingRulings: 'Orzeczenia Karmienia', purificationRulings: 'Orzeczenia Oczyszczenia', comingSoon: 'Wkrótce' },
  dhikr: { currentDhikr: 'Bieżący Dhikr', tapToCount: 'Dotknij, aby Liczyć', resetCount: 'Resetuj Licznik', dhikrNotFound: 'Dhikr nie znaleziony', backToSelection: 'Wróć do Wyboru Dhikr', tasbeehah: 'liczenie', subhanallah: 'SubhanAllah', alhamdulillah: 'Alhamdulillah', allahuakbar: 'Allahu Akbar', lailaha: 'La ilaha illallah', astaghfirullah: 'Astaghfirullah', lahawla: 'La hawla wala quwwata illa billah', subhanallahwabihamdi: 'SubhanAllahi wa bihamdihi', salawat: 'Błogosławieństwa dla Proroka ﷺ', descSubhanallah: 'Wychwalanie Allaha', descAlhamdulillah: 'Chwalenie Allaha', descAllahuakbar: 'Wywyższanie Allaha', descLailaha: 'Wyznanie Wiary', descAstaghfirullah: 'Szukanie Przebaczenia', descLahawla: 'Oświadczenie Zaufania', descSubhanallahwabihamdi: 'Dwa lekkie słowa na języku', descSalawat: 'O Allahu, pobłogosław naszego Proroka Muhammada' },
  tasbeeh: { title: 'Strony Tasbihu', morningAdhkar: 'Poranne Adhkar', eveningAdhkar: 'Wieczorne Adhkar', sleepAdhkar: 'Adhkar Snu', variousAdhkar: 'Różne Adhkar', adhkarCount: 'adhkar', resetAll: 'Resetuj Wszystkie Liczniki', done: 'Gotowe ✓', morningEveningAdhkar: 'Poranne, wieczorne i senne adhkar', customizeSettings: 'Dostosuj kolory, czcionki i interfejs' },
  preparations: { title: 'Przygotowania', quranLearning: 'Święty Koran', quranLearningDesc: 'Nauka Koranu i Tadżwidu', breastfeedingRulings: 'Orzeczenia Karmienia', breastfeedingDesc: 'Orzeczenia fiqh dotyczące karmienia', threeDContent: 'Treść 3D', threeDDesc: 'Interaktywna treść edukacyjna', interactiveMap: 'Interaktywna Mapa', interactiveMapDesc: 'Poznaj świat islamski', mapInfo: 'Zostanie dodana interaktywna mapa świata islamskiego z informacjami o każdym kraju', comingSoon: 'Wkrótce' },
  prayerDetail: { prayer: 'Modlitwa', rakaat: 'Rakaat', fard: 'Obowiązkowy', sunnahBefore: 'Sunna Przed', sunnahAfter: 'Sunna Po', completed: 'Ukończono', required: 'Wymagany', addRakaat: 'Dodaj Raka', completedLabel: 'Ukończono', virtues: 'Zalety', resetCount: 'Resetuj Licznik', prayerNotFound: 'Modlitwa nie znaleziona', backToHome: 'Wróć na Stronę Główną' },
  islamicEvent: {
    practices: 'Zalecane Praktyki', duaOrDhikr: 'Dua lub Dhikr', quranVerses: 'Wersety Koranu', surah: 'Sura', verse: 'Werset', backToCalendar: 'Wróć do Kalendarza', eventNotFound: 'Wydarzenie nie znalezione', month: 'Miesiąc', typeHoliday: 'Święto', typeFasting: 'Post', typeSpecial: 'Specjalne', typeWorship: 'Modlitwa',
    events: {
      newYear: { name: 'Islamski Nowy Rok', description: 'Początek nowego roku Hidżri', fullDescription: '1 Muharram wyznacza początek nowego roku islamskiego, upamiętniając Hidżrę Proroka ﷺ z Mekki do Medyny.', practices: ['Zastanowić się nad minionym rokiem i żałować', 'Ustanowić pobożne zamiary na nowy rok', 'Modlić się o dobro i błogosławieństwa'] },
      ashura: { name: 'Dzień Aszury', description: 'Post Aszury (zalecane pościć też 9.)', fullDescription: 'Aszura to 10. Muharram, dzień w którym Allah uratował Musę i jego lud od Faraona.', practices: ['Pościć 9. i 10. Muharram', 'Zwiększyć dhikr i dua', 'Dawać jałmużnę'] },
      mawlid: { name: 'Urodziny Proroka', description: 'Upamiętnienie narodzin Proroka ﷺ', fullDescription: '12 Rabi al-Awwal wyznacza narodziny Proroka Muhammada ﷺ.', practices: ['Obficie wysyłać błogosławieństwa dla Proroka ﷺ', 'Czytać biografię Proroka', 'Uczyć się z charakteru Proroka ﷺ'] },
      israMiraj: { name: 'Isra i Mi\'radż', description: 'Błogosławiona i wyróżniona noc', fullDescription: 'Nocna Podróż i Wniebowstąpienie to gdy Prorok ﷺ został przeniesiony z Meczetu Świętego do Meczetu al-Aksa.', practices: ['Obficie wysyłać błogosławieństwa dla Proroka ﷺ', 'Odmówić co najmniej dwa rakaty', 'Czytać Surę al-Isra', 'Rozważać cuda Allaha'] },
      nisfShaban: { name: 'Noc Połowy Szabanu', description: 'Noc zmiany Kibli', fullDescription: 'Noc połowy Szabanu to błogosławiona noc, gdy Kibla została zmieniona z Jerozolimy na Kaabę.', practices: ['Zwiększyć dua i istighfar', 'Odmówić qijam al-lajl', 'Rozważać historię zmiany Kibli'] },
      ramadanStart: { name: 'Początek Ramadanu', description: 'Miesiąc postu i Koranu', fullDescription: 'Błogosławiony miesiąc Ramadan to miesiąc postu, modlitwy i recytacji Koranu.', practices: ['Pościć cały miesiąc', 'Czytać i ukończyć Koran', 'Odmawiać Tarawih', 'Zwiększyć jałmużnę'] },
      lastTen: { name: 'Ostatnie Dziesięć Nocy', description: 'Szukanie Lajlat al-Qadr w nieparzyste noce', fullDescription: 'Ostatnie dziesięć nocy Ramadanu zawierają Lajlat al-Qadr, która jest lepsza niż tysiąc miesięcy.', practices: ['Odmawiać qijam w nieparzyste noce (21, 23, 25, 27, 29)', 'Wykonać itikaf w meczecie', 'Zwiększyć dua i dhikr', 'Recytować Koran'] },
      eidFitr: { name: 'Id al-Fitr', description: 'Radość poszczącego i takbirat', fullDescription: 'Id al-Fitr to dzień radości po poście w miesiącu Ramadanie.', practices: ['Recytować takbirat od nocy Id do modlitwy Id', 'Odmówić modlitwę Id', 'Zapłacić Zakat al-Fitr przed modlitwą', 'Odwiedzić krewnych'] },
      arafah: { name: 'Dzień Arafatu', description: 'Najlepszy dzień dla nie-pielgrzymów, post odkupuje dwa lata', fullDescription: 'Dzień Arafatu to 9. Dhul Hidżdża, najlepszy dzień w którym wzeszło słońce.', practices: ['Pościć w Dniu Arafatu (dla nie-pielgrzymów)', 'Zwiększyć dhikr i dua', 'Żałować i szukać przebaczenia'] },
      eidAdha: { name: 'Id al-Adha', description: 'Dzień ofiary i dni Taszrik', fullDescription: 'Id al-Adha to dzień ofiary (10. Dhul Hidżdża) po którym następują dni Taszrik.', practices: ['Recytować takbirat podczas dni Taszrik', 'Odmówić modlitwę Id', 'Złożyć ofiarę', 'Utrzymywać więzi rodzinne'] },
    },
  },
};
