// Ukrainian Translation
import type { TranslationKeys } from './ar';

export const uk: TranslationKeys = {
  app: { name: 'Islami', tagline: 'Твій Ісламський Супутник' },
  nav: { home: 'Головна', quran: 'Коран', hadith: 'Хадис', rulings: 'Правила', sound: 'Аудіо', counters: 'Лічильники', settings: 'Налаштування' },
  home: { prayerTimes: 'Час Молитви', nextPrayer: 'Наступна Молитва', hijriCalendar: 'Хіджрі Календар', today: 'Сьогодні', fajr: 'Фаджр', sunrise: 'Схід', dhuhr: 'Зухр', asr: 'Аср', maghrib: 'Магріб', isha: 'Іша' },
  counters: { title: 'Лічильники', dhikr: 'Зікр', tasbeeh: 'Тасбіх', preparations: 'Підготовка', selectDhikr: 'Вибрати Зікр', count: 'Рахувати', reset: 'Скинути', target: 'Ціль' },
  settings: { title: 'Налаштування', theme: 'Тема', light: 'Світла', dark: 'Темна', auto: 'Автоматична', primaryColor: 'Основний Колір', fontSize: 'Розмір Шрифту', fontFamily: 'Шрифт', background: 'Стиль Фону', navPosition: 'Позиція Навігації', bottom: 'Внизу', right: 'Справа', left: 'Зліва', borderRadius: 'Радіус Кута', spacing: 'Відстань', fontWeight: 'Товщина Шрифту', lineHeight: 'Висота Рядка', letterSpacing: 'Відстань між Літерами', animations: 'Анімації', highContrast: 'Високий Контраст', colorBlind: 'Дальтонізм', reset: 'Скинути', language: 'Мова', selectLanguage: 'Вибрати Мову' },
  colors: { green: 'Ісламський Зелений', gold: 'Золотий', blue: 'Синій', purple: 'Фіолетовий', red: 'Червоний', teal: 'Бірюзовий', orange: 'Помаранчевий', pink: 'Рожевий', indigo: 'Індиго', brown: 'Коричневий' },
  fontSizes: { xsmall: 'Дуже Малий', small: 'Малий', medium: 'Середній', large: 'Великий', xlarge: 'Дуже Великий', xxlarge: 'Величезний' },
  colorBlind: { none: 'Нормальний', protanopia: 'Протанопія', deuteranopia: 'Дейтеранопія', tritanopia: 'Тританопія' },
  common: { loading: 'Завантаження...', error: 'Виникла помилка', retry: 'Повторити', save: 'Зберегти', cancel: 'Скасувати', confirm: 'Підтвердити', back: 'Назад', next: 'Далі', previous: 'Попередній', search: 'Пошук', notFound: 'Не Знайдено', comingSoon: 'Незабаром' },
  calendar: { year: 'Рік', month: 'Місяць', sacredMonth: 'Священний Місяць', whiteDays: 'Білі Дні', islamicEvent: 'Ісламська Подія', currentDay: 'Поточний День', upcomingEvents: 'Майбутні Події', sacredMonths: 'Священні Місяці', tapFullCalendar: 'Натисніть для повного Хіджрі календаря', gregorianDate: 'Григоріанська Дата', hijriYear: 'Х', muharram: 'Мухаррам', safar: 'Сафар', rabiAlAwwal: 'Рабі аль-Авваль', rabiAlThani: 'Рабі ас-Сані', jumadaAlUla: 'Джумада аль-Ула', jumadaAlThani: 'Джумада ас-Санія', rajab: 'Раджаб', shaban: 'Шабан', ramadan: 'Рамадан', shawwal: 'Шавваль', dhuAlQidah: 'Зуль-Кіда', dhuAlHijjah: 'Зуль-Хіджа', monthNum: 'Місяць' },
  quran: { title: 'Священний Коран', searchPlaceholder: 'Пошук сури або аяту...', bookmarks: 'Закладки', lastRead: 'Останнє Прочитане', comingSoon: 'Незабаром', contentComingSoon: 'Зміст Корану буде додано тут', collections: 'Збірки', selectCollection: 'Оберіть збірку', sections: 'Розділи', selectSection: 'Оберіть розділ', hadithNumber: 'Хадис №', arabicText: 'Арабський текст', translation: 'Переклад', loadingHadiths: 'Завантаження хадисів...', errorLoading: 'Помилка завантаження', noHadiths: 'У цьому розділі немає хадисів', totalHadiths: 'Всього хадисів', allCollections: 'Всі збірки', backToCollections: 'Назад до збірок', backToSections: 'Назад до розділів' },
  hadith: { title: 'Хадис', searchPlaceholder: 'Пошук хадису...', sahihBukhari: 'Сахіх аль-Бухарі', sahihMuslim: 'Сахіх Муслім', comingSoon: 'Незабаром', contentComingSoon: 'Хадиси Пророка ﷺ будуть додані тут' },
  sound: { title: 'Рецитації', selectReciter: 'Вибрати Рецитатора', reciters: 'Рецитатори', recitations: 'Рецитації Корану', murattal: 'Мураттал', mujawwad: 'Муджаввад' },
  rulings: { title: 'Правила', searchPlaceholder: 'Пошук правила...', prayerRulings: 'Правила Молитви', fastingRulings: 'Правила Посту', zakatRulings: 'Правила Закату', hajjRulings: 'Правила Хаджу', breastfeedingRulings: 'Правила Годування', purificationRulings: 'Правила Очищення', comingSoon: 'Незабаром' },
  dhikr: { currentDhikr: 'Поточний Зікр', tapToCount: 'Натисніть для Рахунку', resetCount: 'Скинути Лічильник', dhikrNotFound: 'Зікр не знайдено', backToSelection: 'Назад до Вибору Зікру', tasbeehah: 'рахунок', subhanallah: 'СубханАллах', alhamdulillah: 'Альхамдуліллях', allahuakbar: 'Аллаху Акбар', lailaha: 'Ля іляха ілляллах', astaghfirullah: 'Астагфіруллях', lahawla: 'Ля хавла валя куввата ілля біллях', subhanallahwabihamdi: 'СубханАллахі ва біхамдіхі', salawat: 'Благословіння Пророку ﷺ', descSubhanallah: 'Прославлення Аллаха', descAlhamdulillah: 'Хвала Аллаху', descAllahuakbar: 'Звеличення Аллаха', descLailaha: 'Сповідання Віри', descAstaghfirullah: 'Прохання Прощення', descLahawla: 'Заява Довіри', descSubhanallahwabihamdi: 'Два легкі слова на язиці', descSalawat: 'О Аллах, благослови нашого Пророка Мухаммада' },
  tasbeeh: { title: 'Сторінки Тасбіху', morningAdhkar: 'Ранкові Азкар', eveningAdhkar: 'Вечірні Азкар', sleepAdhkar: 'Азкар Сну', variousAdhkar: 'Різні Азкар', adhkarCount: 'азкар', resetAll: 'Скинути Всі Лічильники', done: 'Готово ✓', morningEveningAdhkar: 'Ранкові, вечірні та азкар сну', customizeSettings: 'Налаштувати кольори, шрифти та інтерфейс' },
  preparations: { title: 'Підготовка', quranLearning: 'Священний Коран', quranLearningDesc: 'Вивчення Корану та Таджвіду', breastfeedingRulings: 'Правила Годування', breastfeedingDesc: 'Правила фікху про годування', threeDContent: '3D Контент', threeDDesc: 'Інтерактивний освітній контент', interactiveMap: 'Інтерактивна Карта', interactiveMapDesc: 'Дослідіть ісламський світ', mapInfo: 'Інтерактивна карта ісламського світу з інформацією про кожну країну буде додана', comingSoon: 'Незабаром' },
  prayerDetail: { prayer: 'Молитва', rakaat: 'Ракаат', fard: 'Обов\'язковий', sunnahBefore: 'Сунна Перед', sunnahAfter: 'Сунна Після', completed: 'Завершено', required: 'Необхідний', addRakaat: 'Додати Рака', completedLabel: 'Завершено', virtues: 'Чесноти', resetCount: 'Скинути Лічильник', prayerNotFound: 'Молитву не знайдено', backToHome: 'Назад на Головну' },
  islamicEvent: {
    practices: 'Рекомендовані Практики', duaOrDhikr: 'Дуа або Зікр', quranVerses: 'Аяти Корану', surah: 'Сура', verse: 'Аят', backToCalendar: 'Назад до Календаря', eventNotFound: 'Подію не знайдено', month: 'Місяць', typeHoliday: 'Свято', typeFasting: 'Піст', typeSpecial: 'Особливий', typeWorship: 'Поклоніння',
    events: {
      newYear: { name: 'Ісламський Новий Рік', description: 'Початок нового року Хіджрі', fullDescription: '1 Мухаррам знаменує початок нового ісламського року.', practices: ['Роздумувати про минулий рік і каятися', 'Ставити благочестиві наміри на новий рік', 'Молитися за добро та благословіння'] },
      ashura: { name: 'День Ашура', description: 'Піст Ашура (рекомендовано постити і 9-го)', fullDescription: 'Ашура — 10-й Мухаррам, день коли Аллах врятував Мусу та його народ від Фараона.', practices: ['Постити 9 і 10 Мухаррам', 'Збільшити зікр і дуа', 'Давати милостиню'] },
      mawlid: { name: 'День Народження Пророка', description: 'Вшанування народження Пророка ﷺ', fullDescription: '12 Рабі аль-Авваль знаменує народження Пророка Мухаммада ﷺ.', practices: ['Посилати рясні благословіння Пророку ﷺ', 'Читати біографію Пророка', 'Вчитися з характеру Пророка ﷺ'] },
      israMiraj: { name: 'Ісра і Мірадж', description: 'Благословенна і видатна ніч', fullDescription: 'Нічна Подорож і Вознесіння — коли Пророк ﷺ був перенесений зі Священної Мечеті до Мечеті аль-Акса.', practices: ['Посилати рясні благословіння Пророку ﷺ', 'Молитися щонайменше два ракати', 'Читати Суру аль-Ісра', 'Роздумувати про чудеса Аллаха'] },
      nisfShaban: { name: 'Ніч Середини Шабану', description: 'Ніч зміни Кібли', fullDescription: 'Ніч середини Шабану — благословенна ніч коли Кібла була змінена з Єрусалиму на Каабу.', practices: ['Збільшити дуа та істігфар', 'Молитися кійям аль-лейл', 'Роздумувати про історію зміни Кібли'] },
      ramadanStart: { name: 'Початок Рамадану', description: 'Місяць посту і Корану', fullDescription: 'Благословенний місяць Рамадан — місяць посту, молитви та читання Корану.', practices: ['Постити весь місяць', 'Читати і завершити Коран', 'Молитися Таравіх', 'Збільшити благодійність'] },
      lastTen: { name: 'Останні Десять Ночей', description: 'Шукати Лейлат аль-Кадр у непарних ночах', fullDescription: 'Останні десять ночей Рамадану містять Лейлат аль-Кадр, яка краща за тисячу місяців.', practices: ['Молитися кійям у непарні ночі (21, 23, 25, 27, 29)', 'Здійснити ітікаф у мечеті', 'Збільшити дуа і зікр', 'Читати Коран'] },
      eidFitr: { name: 'Ід аль-Фітр', description: 'Радість постящого і такбірат', fullDescription: 'Ід аль-Фітр — день радості після посту місяця Рамадан.', practices: ['Читати такбірат від ночі Іду до молитви', 'Здійснити молитву Іду', 'Сплатити Закат аль-Фітр перед молитвою', 'Відвідати родичів'] },
      arafah: { name: 'День Арафат', description: 'Найкращий день для не-паломників, піст спокутує два роки', fullDescription: 'День Арафат — 9-й Зуль-Хіджа, найкращий день на який зійшло сонце.', practices: ['Постити в День Арафат (для не-паломників)', 'Збільшити зікр і дуа', 'Каятися і шукати прощення'] },
      eidAdha: { name: 'Ід аль-Адха', description: 'День жертвоприношення і дні Ташрік', fullDescription: 'Ід аль-Адха — день жертвоприношення (10 Зуль-Хіджа) за яким слідують дні Ташрік.', practices: ['Читати такбірат під час днів Ташрік', 'Здійснити молитву Іду', 'Принести жертву', 'Підтримувати сімейні зв\'язки'] },
    },
  },
};
